function out = run_cabin_cooling(cfg)
%RUN_CABIN_COOLING Independent Karachi cabin-load screening module.

p = cfg.cabinCooling;
outputDir = fullfile(cfg.project.outputDir,"cabin_cooling");
ensure_output_folder(outputDir);

out.inputs = read_project_csv(p.files.loadInputs, ...
    {'LoadComponent','Load_kW','CabinSetpoint_C', ...
     'InteriorRelativeHumidity_pct','SourceWorkbook','SourceStatus'}, ...
    {'Load_kW','CabinSetpoint_C','InteriorRelativeHumidity_pct'});
calculated = calculate_cabin_partial_load(out.inputs);
if abs(calculated.RecoveredPartialSensibleLoad_kW- ...
        p.recoveredCabinDuty_kW)>1e-9
    error('EVThermal:CabinLoadMismatch', ...
        'Configured cabin duty does not equal the recovered load-input sum.');
end

out.summary = table(p.designLocation,p.designAmbient_C,p.initialHotSoak_C, ...
    p.ambientRelativeHumidity_pct,p.cabinSetpoint_C, ...
    p.cabinRelativeHumidity_pct, ...
    calculated.RecoveredPartialSensibleLoad_kW,p.modelBoundary, ...
    'VariableNames',{'DesignLocation','DesignAmbient_C','InitialHotSoak_C', ...
    'AmbientRelativeHumidity_pct','CabinSetpoint_C', ...
    'CabinRelativeHumidity_pct','RecoveredPartialSensibleLoad_kW', ...
    'ModelBoundary'});

writetable(out.inputs,fullfile(outputDir,"cabin_load_inputs_used.csv"));
writetable(out.summary,fullfile(outputDir,"cabin_cooling_summary.csv"));
end

function ensure_output_folder(folder)
if ~isfolder(folder)
    mkdir(folder);
end
end
