function results = run_all(cfg)
%RUN_ALL Execute the modular EV thermal analyses in dependency order.

if nargin < 1
    cfg = setup_project();
else
    cfg = setup_project(cfg);
end
rootDir = fileparts(mfilename('fullpath'));
results.config = cfg;
fprintf('%s v%s\n',cfg.project.name,cfg.project.version);

verify_module_paths(rootDir);
if ~isfolder(cfg.project.outputDir)
    mkdir(cfg.project.outputDir);
end

results.motorHeat = run_motor_heat_generation(cfg);
results.motorCooling = run_motor_cooling(cfg,results.motorHeat);
results.batteryCooling = run_battery_cooling(cfg,results.motorHeat);
results.cabinCooling = run_cabin_cooling(cfg);
% Literature-assumption estimates are kept separate from evidence results.
results.literatureGapFill = run_literature_gap_fill(cfg, ...
    results.motorHeat,results.motorCooling);

expectedOutputs = expected_output_files(cfg);
missingOutputs = expectedOutputs(~isfile(expectedOutputs));
if ~isempty(missingOutputs)
    error('EVThermal:MissingOutputs', ...
        'Output completeness check failed. Missing:\n%s', ...
        strjoin(missingOutputs,newline));
end

fprintf('\nAll analyses completed. Results: %s\n',cfg.project.outputDir);
fprintf('Output completeness check passed: %d/%d files present.\n', ...
    numel(expectedOutputs),numel(expectedOutputs));
end

function verify_module_paths(rootDir)
modules = { ...
    'run_motor_heat_generation','motor_heat'; ...
    'run_motor_cooling','motor_cooling'; ...
    'run_battery_cooling','battery_cooling'; ...
    'run_cabin_cooling','cabin_cooling'; ...
    'run_literature_gap_fill','literature_gap_fill'};
for i = 1:size(modules,1)
    resolved = which(modules{i,1});
    expected = fullfile(rootDir,'modules',modules{i,2}, ...
        [modules{i,1} '.m']);
    if ~strcmpi(strrep(resolved,'\','/'),strrep(expected,'\','/'))
        error('EVThermal:PathConflict', ...
            ['MATLAB resolved %s from an unexpected location:\n%s\n' ...
             'Expected:\n%s\nRemove older project copies from the path.'], ...
            modules{i,1},resolved,expected);
    end
end
end

function files = expected_output_files(cfg)
root = cfg.project.outputDir;
fileStems = [cfg.cycles.FileStem;cfg.motorHeat.operatingCases.FileStem];
motorTrace = fullfile(root,"motor_heat",fileStems+"_motor_heat_trace.csv");
motorThermalTrace = fullfile(root,"motor_cooling", ...
    fileStems+"_motor_thermal_trace.csv");

selection = string(cfg.batteryCooling.cycleSelection);
if isscalar(selection) && lower(selection)=="all"
    selection = fileStems;
end
batteryTrace = fullfile(root,"battery_cooling", ...
    selection(:)+"_battery_heat_trace.csv");

files = [motorTrace; motorThermalTrace; batteryTrace; string({ ...
    fullfile(root,'motor_heat','motor_heat_summary.csv'), ...
    fullfile(root,'motor_heat','controller_loss_reference_used.csv'), ...
    fullfile(root,'motor_heat','motor_heat_traces.png'), ...
    fullfile(root,'motor_cooling','motor_thermal_summary.csv'), ...
    fullfile(root,'motor_cooling','motor_thermal_response.png'), ...
    fullfile(root,'motor_cooling','loop_segments.csv'), ...
    fullfile(root,'motor_cooling','loop_sensitivity.csv'), ...
    fullfile(root,'motor_cooling','pump_operating_point.csv'), ...
    fullfile(root,'motor_cooling','loop_sensitivity.png'), ...
    fullfile(root,'motor_cooling','radiator_candidate_geometry.csv'), ...
    fullfile(root,'motor_cooling','radiator_design_requirements.csv'), ...
    fullfile(root,'motor_cooling','radiator_airside_sensitivity.csv'), ...
    fullfile(root,'motor_cooling','radiator_design_requirements.png'), ...
    fullfile(root,'battery_cooling','battery_sustained_screen.csv'), ...
    fullfile(root,'battery_cooling','battery_specification_limits.csv'), ...
    fullfile(root,'battery_cooling','battery_c_rate_sweep.png'), ...
    fullfile(root,'battery_cooling','battery_cycle_heat_summary.csv'), ...
    fullfile(root,'battery_cooling','battery_cycle_heat.png'), ...
    fullfile(root,'cabin_cooling','cabin_load_inputs_used.csv'), ...
    fullfile(root,'cabin_cooling','cabin_cooling_summary.csv'), ...
    fullfile(root,'cabin_cooling','cabin_load_breakdown.png'), ...
    fullfile(root,'cabin_cooling','cabin_workbook_audit.csv'), ...
    fullfile(root,'cabin_cooling','cabin_heat_balance.csv')})'; ...
    fullfile(root,"literature_gap_fill",[ ...
    "literature_assumptions_used.csv";"drive_operating_point_heat.csv"; ...
    "winding_resistance_calibration.csv";"radiator_estimated_performance.csv"; ...
    "radiator_estimated_design_check.csv";"battery_path_budget.csv"; ...
    "battery_coolant_envelope_comparison.csv";"battery_discharge_summary.csv"; ...
    "cabin_workbook_audit.csv";"cabin_heat_balance.csv"; ...
    "cabin_pull_down_capacity.csv";"gap_drive_operating_points.png"; ...
    "gap_motor_resistance_calibration.png";"gap_radiator_performance_map.png"; ...
    "gap_battery_heat_and_path.png";"gap_battery_discharge_transient.png"; ...
    "gap_cabin_heat_balance.png";"correction_robustness.csv"; ...
    "correction_sensitivity.csv";"gap_correction_robustness.png"; ...
    "reference_checks.csv"])];
end
