function results = run_all(cfg)
%RUN_ALL Execute the configured EV thermal analyses.
%   results = RUN_ALL() uses system_config.m in the project root.
%   results = RUN_ALL(cfg) uses a caller-supplied configuration struct.

if nargin < 1
    cfg = setup_project();
else
    cfg = setup_project(cfg);
end
rootDir = fileparts(mfilename('fullpath'));
results.config = cfg;
fprintf('%s v%s\n',cfg.project.name,cfg.project.version);

requiredFunctions = {'run_battery_analysis', 'run_drive_unit_analysis', ...
    'run_cooling_loop_analysis', 'run_cabin_load_analysis', ...
    'run_drive_cycle_analysis'};
for i = 1:numel(requiredFunctions)
    resolvedFile = which(requiredFunctions{i});
    expectedFile = fullfile(rootDir, 'examples', [requiredFunctions{i} '.m']);
    normalizedResolved = strrep(resolvedFile, '\', '/');
    normalizedExpected = strrep(expectedFile, '\', '/');
    if ~strcmpi(normalizedResolved, normalizedExpected)
        error('EVThermal:PathConflict', ...
            ['MATLAB resolved %s from an unexpected location:\n%s\n' ...
             'Expected:\n%s\nRemove older copies of this project from the path.'], ...
            requiredFunctions{i}, resolvedFile, expectedFile);
    end
end

if ~exist(cfg.project.outputDir, 'dir')
    mkdir(cfg.project.outputDir);
end

results.battery = run_battery_analysis(cfg);
results.driveCycles = run_drive_cycle_analysis(cfg);
results.driveUnit = run_drive_unit_analysis(cfg,results.driveCycles.summary);
results.hydraulics = run_cooling_loop_analysis(cfg);
results.cabin = run_cabin_load_analysis(cfg);

expectedOutputs = { ...
    'battery_heat_generation.png', ...
    'battery_heat_results.csv', ...
    'battery_load_cases.csv', ...
    'cabin_partial_load_result.csv', ...
    'cooling_loop_segment_results.csv', ...
    'cooling_loop_sensitivity.png', ...
    'cooling_loop_sensitivity_results.csv', ...
    'inactive_pump_resistance_cases.csv', ...
    'drive_unit_coolant_results.csv', ...
    'drive_unit_heat_breakdown.png', ...
    'drive_unit_heat_results.csv', ...
    'radiator_requirement.csv', ...
    'drive_unit_thermal_reference.csv'};

cycleOutputs = cellstr(cfg.cycles.FileStem + "_transient_results.csv");
expectedOutputs = [expectedOutputs, cycleOutputs', { ...
    'drive_cycle_thermal_summary.csv', ...
    'drive_cycle_compressor_comparison.csv', ...
    'compressor_candidate_specifications.csv', ...
    'pump_operating_point_check.csv', ...
    'drive_cycle_thermal_traces.png'}];

outputPaths = cellfun(@(name) fullfile(cfg.project.outputDir, name), ...
    expectedOutputs, 'UniformOutput', false);
missingOutputs = expectedOutputs(~cellfun(@isfile, outputPaths));
if ~isempty(missingOutputs)
    error('EVThermal:MissingOutputs', ...
        'Output completeness check failed. Missing:\n%s', ...
        strjoin(missingOutputs, '\n'));
end

fprintf('\nAll analyses completed. Results: %s\n', cfg.project.outputDir);
fprintf('Output completeness check passed: %d/%d files present.\n', ...
    numel(expectedOutputs), numel(expectedOutputs));
end
