function results = run_all(cfg)
%RUN_ALL Execute the modular EV thermal analyses in dependency order.

if nargin < 1
    cfg = setup_project();
else
    cfg = setup_project(cfg);
end
rootDir = fileparts(mfilename('fullpath'));
results.config = cfg;
fprintf('%s v%s\n',cfg.project.name,cfg.project.version);

verify_module_paths(rootDir);
if ~isfolder(cfg.project.outputDir)
    mkdir(cfg.project.outputDir);
end

results.motorHeat = run_motor_heat_generation(cfg);
results.motorCooling = run_motor_cooling(cfg,results.motorHeat);
results.batteryCooling = run_battery_cooling(cfg,results.motorHeat);
results.cabinCooling = run_cabin_cooling(cfg);
results.sharedCompressor = run_shared_compressor( ...
    cfg,results.batteryCooling,results.cabinCooling);

expectedOutputs = expected_output_files(cfg);
missingOutputs = expectedOutputs(~isfile(expectedOutputs));
if ~isempty(missingOutputs)
    error('EVThermal:MissingOutputs', ...
        'Output completeness check failed. Missing:\n%s', ...
        strjoin(missingOutputs,newline));
end

fprintf('\nAll analyses completed. Results: %s\n',cfg.project.outputDir);
fprintf('Output completeness check passed: %d/%d files present.\n', ...
    numel(expectedOutputs),numel(expectedOutputs));
end

function verify_module_paths(rootDir)
modules = { ...
    'run_motor_heat_generation','motor_heat'; ...
    'run_motor_cooling','motor_cooling'; ...
    'run_battery_cooling','battery_cooling'; ...
    'run_cabin_cooling','cabin_cooling'; ...
    'run_shared_compressor','shared_compressor'};
for i = 1:size(modules,1)
    resolved = which(modules{i,1});
    expected = fullfile(rootDir,'modules',modules{i,2}, ...
        [modules{i,1} '.m']);
    if ~strcmpi(strrep(resolved,'\','/'),strrep(expected,'\','/'))
        error('EVThermal:PathConflict', ...
            ['MATLAB resolved %s from an unexpected location:\n%s\n' ...
             'Expected:\n%s\nRemove older project copies from the path.'], ...
            modules{i,1},resolved,expected);
    end
end
end

function files = expected_output_files(cfg)
root = cfg.project.outputDir;
motorTrace = fullfile(root,"motor_heat", ...
    cfg.cycles.FileStem+"_motor_heat_trace.csv");
batteryTrace = fullfile(root,"battery_cooling", ...
    cfg.cycles.FileStem+"_battery_cooling_trace.csv");

files = [motorTrace; batteryTrace; string({ ...
    fullfile(root,'motor_heat','motor_heat_summary.csv'), ...
    fullfile(root,'motor_heat','motor_heat_traces.png'), ...
    fullfile(root,'motor_cooling','motor_heat_boundary.csv'), ...
    fullfile(root,'motor_cooling','coolant_transport.csv'), ...
    fullfile(root,'motor_cooling','radiator_requirement.csv'), ...
    fullfile(root,'motor_cooling','motor_thermal_reference.csv'), ...
    fullfile(root,'motor_cooling','radiator_geometry.csv'), ...
    fullfile(root,'motor_cooling','loop_segments.csv'), ...
    fullfile(root,'motor_cooling','loop_sensitivity.csv'), ...
    fullfile(root,'motor_cooling','pump_operating_point.csv'), ...
    fullfile(root,'motor_cooling','inactive_pump_cases.csv'), ...
    fullfile(root,'motor_cooling','loop_sensitivity.png'), ...
    fullfile(root,'motor_cooling','motor_cooling_current_result.csv'), ...
    fullfile(root,'motor_cooling','motor_cooling_requirements.png'), ...
    fullfile(root,'battery_cooling','battery_cooling_summary.csv'), ...
    fullfile(root,'battery_cooling','battery_constant_current_sensitivity.csv'), ...
    fullfile(root,'battery_cooling','battery_reference_cases.csv'), ...
    fullfile(root,'battery_cooling','battery_heat_exchanger_geometry.csv'), ...
    fullfile(root,'battery_cooling','battery_cooling_traces.png'), ...
    fullfile(root,'cabin_cooling','cabin_load_inputs_used.csv'), ...
    fullfile(root,'cabin_cooling','cabin_cooling_summary.csv'), ...
    fullfile(root,'cabin_cooling','cabin_load_breakdown.png'), ...
    fullfile(root,'shared_compressor','compressor_map_operating_point.csv'), ...
    fullfile(root,'shared_compressor','compressor_candidates.csv'), ...
    fullfile(root,'shared_compressor','shared_compressor_comparison.csv'), ...
    fullfile(root,'shared_compressor','shared_cooling_current_result.csv'), ...
    fullfile(root,'shared_compressor','shared_compressor_capacity.png')})'];
end
