function cfg = setup_project(cfg)
%SETUP_PROJECT Add modular folders to the path and validate configuration.

rootDir = fileparts(mfilename('fullpath'));
requiredFolders = { ...
    fullfile(rootDir,'config'), ...
    fullfile(rootDir,'src','calculations'), ...
    fullfile(rootDir,'src','io'), ...
    fullfile(rootDir,'src','validation'), ...
    fullfile(rootDir,'models','battery_requirements'), ...
    fullfile(rootDir,'models','propulsion_thermal_sensitivity'), ...
    fullfile(rootDir,'tests'), ...
    fullfile(rootDir,'modules','motor_heat'), ...
    fullfile(rootDir,'modules','motor_cooling'), ...
    fullfile(rootDir,'modules','battery_cooling'), ...
    fullfile(rootDir,'modules','cabin_cooling')};

for i = 1:numel(requiredFolders)
    if ~isfolder(requiredFolders{i})
        error('EVThermal:MissingProjectFolder', ...
            'Required project folder not found: %s',requiredFolders{i});
    end
    addpath(requiredFolders{i},'-begin');
end
rehash;

if nargin < 1
    cfg = project_config(string(rootDir));
end
validate_system_config(cfg);
end
