%RUN_SANITY_CHECKS Regression and interface checks for the sample dataset.
rootDir = fileparts(fileparts(mfilename('fullpath')));
addpath(rootDir,'-begin');

% Exercise the same clean-start entry point used by run_all. This catches
% startup path failures before any calculation tests are executed.
cfg = setup_project();
assert(strcmp(cfg.project.version,"2.0.5"));

% Import every project-controlled CSV through the same explicit reader used
% by the analyses. This prevents automatic delimiter or header detection
% from reaching a calculation function.
csvChecks = { ...
    cfg.files.vehicleLoadCases, ...
        {'LoadCase','Description','WheelPower_W','MotorPower_W','Current_A','Status'}, ...
        {'WheelPower_W','MotorPower_W','Current_A'}; ...
    cfg.files.cabinLoadInputs, ...
        {'LoadComponent','Load_kW','CabinSetpoint_C','InteriorRelativeHumidity_pct','SourceWorkbook','SourceStatus'}, ...
        {'Load_kW','CabinSetpoint_C','InteriorRelativeHumidity_pct'}; ...
    cfg.files.compressorMap, ...
        {'RPM','EvaporatorTemperature_C','CoolingCapacity_kW','InputPower_kW','Current_A','COP_WW','EvidenceStatus'}, ...
        {'RPM','EvaporatorTemperature_C','CoolingCapacity_kW','InputPower_kW','Current_A','COP_WW'}; ...
    cfg.files.driveEfficiencyMap, ...
        {'Speed_rpm','Torque_Nm','IntegratedEfficiency_pct'}, ...
        {'Speed_rpm','Torque_Nm','IntegratedEfficiency_pct'}; ...
    cfg.files.driveThermalReference, ...
        {'ReferenceCase','CoolantInlet_C','CoolantFlow_Lmin','ReportedWindingTemperature_C','Duration_s','EvidenceStatus'}, ...
        {'CoolantInlet_C','CoolantFlow_Lmin','ReportedWindingTemperature_C','Duration_s'}; ...
    cfg.files.inactivePumpCurve, ...
        {'Flow_Lmin','Flow_Lh','InactivePumpResistance_kPa','DigitizationUncertainty_kPa','EvidenceStatus'}, ...
        {'Flow_Lmin','Flow_Lh','InactivePumpResistance_kPa','DigitizationUncertainty_kPa'}; ...
    cfg.files.heatExchangerGeometry, ...
        {'Radiator','Application','CoreHeight_mm','CoreWidth_mm','FrontalArea_m2','TubeWidth_mm','TubeThickness_mm','TubeQuantity','TubeLength_mm','FinWidth_mm','FinHeight_mm','FinPitch_mm','FinQuantity','FinLength_mm','EvidenceStatus'}, ...
        {'CoreHeight_mm','CoreWidth_mm','FrontalArea_m2','TubeWidth_mm','TubeThickness_mm','TubeQuantity','TubeLength_mm','FinWidth_mm','FinHeight_mm','FinPitch_mm','FinQuantity','FinLength_mm'}; ...
    cfg.files.parameterRegister, ...
        {'ID','Domain','Parameter','Value','Unit','EvidenceClass','Limitation'}, ...
        {}};
for i = 1:size(csvChecks,1)
    imported = read_project_csv(csvChecks{i,1},csvChecks{i,2},csvChecks{i,3});
    assert(width(imported)==numel(csvChecks{i,2}));
end

heat = calculate_battery_ohmic_heat([1;2],cfg.battery.capacity_Ah, ...
    cfg.battery.resistanceProxy_Ohm,cfg.battery.seriesCells);
assert(abs(heat.PackHeat_kW(1)-0.7756992)<1e-8);
assert(abs(heat.PackHeat_kW(2)-3.1027968)<1e-8);

nominal = cfg.coolant(cfg.coolant.Temperature_C==40,:);
transport = calculate_coolant_transport([1;2], ...
    cfg.propulsionCooling.designFlow_Lmin,cfg.propulsionCooling.hoseID_m, ...
    nominal.Density_kgm3,nominal.Cp_JkgK);
assert(abs(transport.HoseVelocity_ms(1)-1.061032954)<1e-8);
assert(transport.CoolantRise_C(2)>transport.CoolantRise_C(1));

[~,hyd] = calculate_cooling_loop_losses(cfg.coolingLoop,16, ...
    nominal.Density_kgm3,nominal.Viscosity_Pas);
assert(abs(hyd.IllustrativeSubtotalIncludingRadiatorRoute_kPa-59.64)<0.15);

inputs = read_project_csv(cfg.files.cabinLoadInputs, ...
    {'LoadComponent','Load_kW','CabinSetpoint_C', ...
     'InteriorRelativeHumidity_pct','SourceWorkbook','SourceStatus'}, ...
    {'Load_kW','CabinSetpoint_C','InteriorRelativeHumidity_pct'});
cabin = calculate_cabin_partial_load(inputs);
assert(abs(cabin.RecoveredPartialSensibleLoad_kW-cfg.hvac.recoveredCabinDuty_kW)<1e-9);

map = read_project_csv(cfg.files.compressorMap, ...
    {'RPM','EvaporatorTemperature_C','CoolingCapacity_kW','InputPower_kW', ...
     'Current_A','COP_WW','EvidenceStatus'}, ...
    {'RPM','EvaporatorTemperature_C','CoolingCapacity_kW','InputPower_kW', ...
     'Current_A','COP_WW'});
compressor = evaluate_compressor_map(map, ...
    cfg.hvac.compressorMapSpeed_rpm,cfg.hvac.compressorMapEvaporator_C);
assert(abs(compressor.CoolingCapacity_kW-3.63)<1e-9);

inactiveCurve = read_project_csv(cfg.files.inactivePumpCurve, ...
    {'Flow_Lmin','Flow_Lh','InactivePumpResistance_kPa', ...
     'DigitizationUncertainty_kPa','EvidenceStatus'}, ...
    {'Flow_Lmin','Flow_Lh','InactivePumpResistance_kPa', ...
     'DigitizationUncertainty_kPa'});
inactiveLoss = interpolate_inactive_pump_resistance(inactiveCurve,20);
assert(inactiveLoss>20 && inactiveLoss<27);

% Regression: accept harmless header normalization performed by MATLAB or
% spreadsheet software without weakening curve-content validation.
renamedCurve = inactiveCurve(:,[1 3]);
renamedCurve.Properties.VariableNames = {'Flow_L_min','PressureDrop_kPa'};
renamedLoss = interpolate_inactive_pump_resistance(renamedCurve,20);
assert(abs(renamedLoss-inactiveLoss)<1e-12);

pumpProperty = cfg.coolant(cfg.coolant.Temperature_C==cfg.pump.checkTemperature_C,:);
[~,pumpDuty] = calculate_cooling_loop_losses(cfg.coolingLoop, ...
    cfg.pump.referenceFlow_Lmin,pumpProperty.Density_kgm3, ...
    pumpProperty.Viscosity_Pas);
assert(pumpDuty.EvidenceBackedPartialSubtotal_kPa>cfg.pump.minimumHead_kPa);
assert(pumpDuty.KnownComponentAllowance_kPa> ...
    pumpDuty.ExternalHoseMajorLoss_kPa+pumpDuty.ExternalFittingMinorLoss_kPa);

curves = load_propulsion_curves(cfg.files.driveLimitWorkbook, ...
    cfg.files.driveEfficiencyMap);
cycleResults = cell(height(cfg.cycles),1);
summaries = cell(height(cfg.cycles),1);
for i = 1:height(cfg.cycles)
    cycle = read_drive_cycle(cfg.cycles.File(i),cfg.cycles.Name(i));
    result = calculate_drive_cycle_thermal(cycle,cfg.vehicle,cfg.battery,curves);
    result = simulate_battery_thermal_state(result,cfg.battery, ...
        cfg.battery.coolantTemperature_C,cfg.battery.initialCellTemperature_C);
    assert(all(isfinite(result.DriveUnitHeat_kW)));
    assert(all(result.BatteryHeat_kW>=0));
    assert(all(result.EstimatedCellTemperature_C<cfg.battery.maximumCell_C));
    peakCellHeat_W = max(result.BatteryHeat_kW)*1000/cfg.battery.seriesCells;
    peakBasePathCell_C = cfg.battery.coolantTemperature_C+ ...
        peakCellHeat_W*cfg.battery.baseResistance_KW;
    assert(peakBasePathCell_C<cfg.battery.maximumCell_C);
    assert(all(result.TorqueWithinCurve));
    assert(all(result.PowerWithinCurve));
    cycleResults{i} = result;
    summaries{i} = summarize_drive_cycle(result);
end

summary = vertcat(summaries{:});
assert(all(abs(summary.AverageDriveUnitHeat_kW.*summary.Duration_s- ...
    3600*summary.DriveUnitHeatEnergy_kWh)<1e-8));
assert(all(abs(summary.AverageBatteryHeat_kW.*summary.Duration_s- ...
    3600*summary.BatteryHeatEnergy_kWh)<1e-8));
driveUnit = run_drive_unit_analysis(cfg,summary);
assert(height(driveUnit.heat)==2*height(cfg.cycles));
assert(all(driveUnit.radiator.RequiredDuty_kW==driveUnit.heat.ThermalDuty_kW));
assert(all(abs(driveUnit.radiator.CoolantOut_C- ...
    (cfg.propulsionCooling.radiatorCoolantIn_C-driveUnit.coolant.CoolantRise_C))<1e-10));

comparison = calculate_cycle_compressor_check( ...
    cycleResults{end},cfg.hvac.compressorCandidates, ...
    cfg.hvac.recoveredCabinDuty_kW,cfg.hvac.allocationPriority);
assert(comparison.Capacity_kW(2)>comparison.Capacity_kW(1));

fprintf('All EV thermal framework sanity checks passed.\n');
