%RUN_SANITY_CHECKS Regression and module-interface checks.
rootDir = fileparts(fileparts(mfilename('fullpath')));
addpath(rootDir,'-begin');
cfg = setup_project();
assert(strcmp(cfg.project.version,"3.0.0-rc1"));

% Every active CSV is imported through the deterministic project reader.
csvChecks = { ...
    cfg.batteryCooling.files.vehicleLoadCases, ...
        {'LoadCase','Description','WheelPower_W','MotorPower_W','Current_A','Status'}, ...
        {'WheelPower_W','MotorPower_W','Current_A'}; ...
    cfg.batteryCooling.files.heatExchangerGeometry, ...
        radiator_columns(),radiator_numeric_columns(); ...
    cfg.cabinCooling.files.loadInputs, ...
        {'LoadComponent','Load_kW','CabinSetpoint_C','InteriorRelativeHumidity_pct','SourceWorkbook','SourceStatus'}, ...
        {'Load_kW','CabinSetpoint_C','InteriorRelativeHumidity_pct'}; ...
    cfg.sharedCompressor.files.performanceMap, ...
        {'RPM','EvaporatorTemperature_C','CoolingCapacity_kW','InputPower_kW','Current_A','COP_WW','EvidenceStatus'}, ...
        {'RPM','EvaporatorTemperature_C','CoolingCapacity_kW','InputPower_kW','Current_A','COP_WW'}; ...
    cfg.sharedCompressor.files.candidates, ...
        {'Model','Displacement_cc','CoolingCapacity_kW','InputPower_kW','Speed_rpm','Voltage_V','EvidenceCondition'}, ...
        {'Displacement_cc','CoolingCapacity_kW','InputPower_kW','Speed_rpm','Voltage_V'}; ...
    cfg.motorHeat.files.driveEfficiencyMap, ...
        {'Speed_rpm','Torque_Nm','IntegratedEfficiency_pct'}, ...
        {'Speed_rpm','Torque_Nm','IntegratedEfficiency_pct'}; ...
    cfg.motorCooling.files.thermalReference, ...
        {'ReferenceCase','CoolantInlet_C','CoolantFlow_Lmin','ReportedWindingTemperature_C','Duration_s','EvidenceStatus'}, ...
        {'CoolantInlet_C','CoolantFlow_Lmin','ReportedWindingTemperature_C','Duration_s'}; ...
    cfg.motorCooling.files.inactivePumpCurve, ...
        {'Flow_Lmin','Flow_Lh','InactivePumpResistance_kPa','DigitizationUncertainty_kPa','EvidenceStatus'}, ...
        {'Flow_Lmin','Flow_Lh','InactivePumpResistance_kPa','DigitizationUncertainty_kPa'}; ...
    cfg.motorCooling.files.radiatorGeometry, ...
        radiator_columns(),radiator_numeric_columns(); ...
    cfg.project.parameterRegister, ...
        {'ID','Domain','Parameter','Value','Unit','EvidenceClass','Limitation'}, ...
        {}};
for i = 1:size(csvChecks,1)
    imported = read_project_csv(csvChecks{i,1},csvChecks{i,2},csvChecks{i,3});
    assert(width(imported)==numel(csvChecks{i,2}));
end

% Core calculation regressions retained from the verified v2.0.5 model.
battery = cfg.batteryCooling;
heat = calculate_battery_ohmic_heat([1;2],battery.capacity_Ah, ...
    battery.resistanceProxy_Ohm,battery.seriesCells);
assert(abs(heat.PackHeat_kW(1)-0.7756992)<1e-8);
assert(abs(heat.PackHeat_kW(2)-3.1027968)<1e-8);

coolant = cfg.motorCooling.coolant;
nominal = coolant(coolant.Temperature_C==40,:);
transport = calculate_coolant_transport([1;2], ...
    cfg.motorCooling.thermal.designFlow_Lmin, ...
    cfg.motorCooling.thermal.hoseID_m, ...
    nominal.Density_kgm3,nominal.Cp_JkgK);
assert(abs(transport.HoseVelocity_ms(1)-1.061032954)<1e-8);
assert(transport.CoolantRise_C(2)>transport.CoolantRise_C(1));

[~,hydraulic] = calculate_cooling_loop_losses( ...
    cfg.motorCooling.loop,16,nominal.Density_kgm3,nominal.Viscosity_Pas);
assert(abs(hydraulic.IllustrativeSubtotalIncludingRadiatorRoute_kPa-59.64)<0.15);

cabinInputs = read_project_csv(cfg.cabinCooling.files.loadInputs, ...
    {'LoadComponent','Load_kW','CabinSetpoint_C', ...
     'InteriorRelativeHumidity_pct','SourceWorkbook','SourceStatus'}, ...
    {'Load_kW','CabinSetpoint_C','InteriorRelativeHumidity_pct'});
cabin = calculate_cabin_partial_load(cabinInputs);
assert(abs(cabin.RecoveredPartialSensibleLoad_kW- ...
    cfg.cabinCooling.recoveredCabinDuty_kW)<1e-9);

compressorMap = read_project_csv(cfg.sharedCompressor.files.performanceMap, ...
    {'RPM','EvaporatorTemperature_C','CoolingCapacity_kW','InputPower_kW', ...
     'Current_A','COP_WW','EvidenceStatus'}, ...
    {'RPM','EvaporatorTemperature_C','CoolingCapacity_kW','InputPower_kW', ...
     'Current_A','COP_WW'});
compressor = evaluate_compressor_map(compressorMap, ...
    cfg.sharedCompressor.mapSpeed_rpm,cfg.sharedCompressor.mapEvaporator_C);
assert(abs(compressor.CoolingCapacity_kW-3.63)<1e-9);

inactiveCurve = read_project_csv(cfg.motorCooling.files.inactivePumpCurve, ...
    {'Flow_Lmin','Flow_Lh','InactivePumpResistance_kPa', ...
     'DigitizationUncertainty_kPa','EvidenceStatus'}, ...
    {'Flow_Lmin','Flow_Lh','InactivePumpResistance_kPa', ...
     'DigitizationUncertainty_kPa'});
inactiveLoss = interpolate_inactive_pump_resistance(inactiveCurve,20);
assert(inactiveLoss>20 && inactiveLoss<27);

% The module boundary is verified directly: the motor trace contains no
% battery heat or cell temperature until it enters the battery module.
curves = load_propulsion_curves(cfg.motorHeat.files.driveLimitWorkbook, ...
    cfg.motorHeat.files.driveEfficiencyMap);
for i = 1:height(cfg.cycles)
    cycle = read_drive_cycle(cfg.cycles.File(i),cfg.cycles.Name(i));
    motorTrace = calculate_motor_operating_trace(cycle,cfg.vehicle,curves);
    assert(~ismember('BatteryHeat_kW',motorTrace.Properties.VariableNames));
    assert(all(isfinite(motorTrace.DriveUnitHeat_kW)));
    assert(all(motorTrace.TorqueWithinCurve));
    assert(all(motorTrace.PowerWithinCurve));

    batteryTrace = calculate_battery_thermal_trace(motorTrace,battery);
    assert(all(batteryTrace.BatteryHeat_kW>=0));
    assert(all(batteryTrace.EstimatedCellTemperature_C<=battery.maximumCell_C));
end

% verify_framework calls run_all before this script. When started directly,
% execute the same complete workflow before checking integrated outputs.
if ~exist('results','var') || ~isstruct(results) || ...
        ~isfield(results,'sharedCompressor')
    results = run_all(cfg); %#ok<NASGU>
end
assert(isfield(results,'motorHeat'));
assert(isfield(results,'motorCooling'));
assert(isfield(results,'batteryCooling'));
assert(isfield(results,'cabinCooling'));
assert(isfield(results,'sharedCompressor'));
assert(height(results.motorHeat.summary)==height(cfg.cycles));
assert(height(results.batteryCooling.summary)==height(cfg.cycles));
assert(all(results.motorCooling.radiator.RequiredDuty_kW== ...
    results.motorCooling.heat.ThermalDuty_kW));
assert(all(results.sharedCompressor.currentResult.KarachiDesignAmbient_C==45));
assert(all(strlength(results.sharedCompressor.currentResult.CabinModelBoundary)>0));
assert(all(strlength(results.sharedCompressor.currentResult.BatteryModelBoundary)>0));
assert(all(results.sharedCompressor.currentResult.OverallScreeningPass== ...
    (results.sharedCompressor.currentResult.GrossCapacityPass & ...
     results.sharedCompressor.currentResult.BatteryTemperatureWithinLimit)));
assert(all(ismember(results.sharedCompressor.currentResult.Cycle, ...
    results.batteryCooling.summary.Cycle)));

fprintf('All modular EV thermal framework sanity checks passed.\n');

function names = radiator_columns()
names = {'Radiator','Application','CoreHeight_mm','CoreWidth_mm', ...
    'FrontalArea_m2','TubeWidth_mm','TubeThickness_mm','TubeQuantity', ...
    'TubeLength_mm','FinWidth_mm','FinHeight_mm','FinPitch_mm', ...
    'FinQuantity','FinLength_mm','EvidenceStatus'};
end

function names = radiator_numeric_columns()
names = {'CoreHeight_mm','CoreWidth_mm','FrontalArea_m2','TubeWidth_mm', ...
    'TubeThickness_mm','TubeQuantity','TubeLength_mm','FinWidth_mm', ...
    'FinHeight_mm','FinPitch_mm','FinQuantity','FinLength_mm'};
end
