%RUN_SANITY_CHECKS Regression, energy-balance and module-boundary checks.
rootDir = fileparts(fileparts(mfilename('fullpath')));
addpath(rootDir,'-begin');
cfg = setup_project();
assert(strcmp(cfg.project.version,"4.2.0"));
assert(~isfield(cfg,'sharedCompressor'));

% Every active CSV is imported through the deterministic project reader.
csvChecks = { ...
    cfg.cabinCooling.files.loadInputs, ...
        {'LoadComponent','Load_kW','CabinSetpoint_C','InteriorRelativeHumidity_pct','SourceWorkbook','SourceStatus'}, ...
        {'Load_kW','CabinSetpoint_C','InteriorRelativeHumidity_pct'}; ...
    cfg.motorHeat.files.driveEfficiencyMap, ...
        {'Speed_rpm','Torque_Nm','IntegratedEfficiency_pct'}, ...
        {'Speed_rpm','Torque_Nm','IntegratedEfficiency_pct'}; ...
    cfg.motorCooling.files.thermalReference, ...
        {'ReferenceCase','CoolantInlet_C','CoolantFlow_Lmin','ReportedWindingTemperature_C','Duration_s','EvidenceStatus'}, ...
        {'CoolantInlet_C','CoolantFlow_Lmin','ReportedWindingTemperature_C','Duration_s'}; ...
    cfg.motorCooling.files.inactivePumpCurve, ...
        {'Flow_Lmin','Flow_Lh','InactivePumpResistance_kPa','DigitizationUncertainty_kPa','EvidenceStatus'}, ...
        {'Flow_Lmin','Flow_Lh','InactivePumpResistance_kPa','DigitizationUncertainty_kPa'}; ...
    cfg.motorCooling.files.radiatorGeometry, ...
        propulsion_radiator_columns(),radiator_numeric_columns(); ...
    cfg.project.parameterRegister, ...
        {'ID','Domain','Parameter','Value','Unit','EvidenceClass','Limitation'}, ...
        {}};
for i = 1:size(csvChecks,1)
    imported = read_project_csv(csvChecks{i,1},csvChecks{i,2},csvChecks{i,3});
    assert(width(imported)==numel(csvChecks{i,2}));
end

% Battery output is sustained and independent of motor or compressor state.
battery = cfg.batteryCooling;
screen = calculate_battery_ohmic_heat([1;2],battery.capacity_Ah, ...
    battery.resistanceProxy_Ohm,battery.seriesCells);
assert(abs(screen.PackHeat_kW(1)-0.7756992)<1e-8);
assert(abs(screen.PackHeat_kW(2)-3.1027968)<1e-8);
riseAtOneC = screen.CellHeat_W(1)*battery.baseResistance_KW;
assert(abs(riseAtOneC-22.26544)<1e-8);
assert(abs((battery.absoluteOperatingLimit_C-riseAtOneC)-37.73456)<1e-8);

batteryRequirements = calculate_battery_requirements_screen([1;2],battery);
assert(isequal(batteryRequirements.PackHeat_kW,screen.PackHeat_kW));
assert(abs(batteryRequirements.RequiredCellToCoolantRise_C(1)-22.26544)<1e-8);
assert(abs(batteryRequirements.MaximumCoolantForRegen_C(1)-32.73456)<1e-8);
assert(abs(batteryRequirements.MaximumCoolantForDischarge_C(1)-37.73456)<1e-8);
assert(all(batteryRequirements.ACRProxyOnly));

% Core coolant transport and hydraulic regressions.
coolant = cfg.motorCooling.coolant;
nominal = coolant(coolant.Temperature_C==40,:);
transport = calculate_coolant_transport([1;2], ...
    cfg.motorCooling.thermal.designFlow_Lmin, ...
    cfg.motorCooling.thermal.hoseID_m, ...
    nominal.Density_kgm3,nominal.Cp_JkgK);
assert(abs(transport.HoseVelocity_ms(1)-1.061032954)<1e-8);

[~,hydraulic] = calculate_cooling_loop_losses( ...
    cfg.motorCooling.loop,20, ...
    coolant.Density_kgm3(coolant.Temperature_C==60), ...
    coolant.Viscosity_Pas(coolant.Temperature_C==60));
assert(abs(hydraulic.EvidenceBackedPartialSubtotal_kPa-71.355)<0.15);
assert(hydraulic.EvidenceBackedPartialSubtotal_kPa> ...
    cfg.motorCooling.pump.minimumHead_kPa);

% Cabin workbook is the authoritative source for the surface-load subtotal.
surfaceLoads_W = readmatrix(cfg.cabinCooling.files.sourceWorkbook, ...
    'Sheet','Sheet1','Range','I2:I18');
assert(abs(sum(surfaceLoads_W,'omitnan')/1000-3.33594)<1e-8);

% verify_framework calls run_all before this script. When started directly,
% execute the complete workflow before checking integrated outputs.
if ~exist('results','var') || ~isstruct(results) || ...
        ~isfield(results,'cabinCooling')
    results = run_all(cfg); %#ok<NASGU>
end
assert(isfield(results,'motorHeat'));
assert(isfield(results,'motorCooling'));
assert(isfield(results,'batteryCooling'));
assert(isfield(results,'cabinCooling'));
assert(~isfield(results,'sharedCompressor'));
assert(height(results.motorHeat.summary)== ...
    height(cfg.cycles)+height(cfg.motorHeat.operatingCases));
assert(height(results.motorCooling.summary)==height(results.motorHeat.summary));
assert(height(results.batteryCooling.screen)==numel(battery.cRates));
assert(all(results.batteryCooling.screen.ACRProxyOnly));
assert(~ismember('EstimatedCellTemperature_C', ...
    results.batteryCooling.screen.Properties.VariableNames));
assert(~ismember('BatteryCoolingRequest_kW', ...
    results.batteryCooling.screen.Properties.VariableNames));
assert(all(abs(results.motorCooling.summary.EnergyBalanceResidual_kWh)<2e-3));
assert(~results.motorCooling.hydraulics.pumpCheck.DocumentedPointCoversPartialLoop);
assert(contains(results.motorCooling.hydraulics.pumpCheck.Conclusion,"fails"));
assert(abs(results.cabinCooling.summary.WorkbookBodyAndGlazingLoad_kW- ...
    3.33594)<1e-8);

fprintf('All simplified EV thermal framework checks passed.\n');

function names = radiator_numeric_columns()
names = {'CoreHeight_mm','CoreWidth_mm','FrontalArea_m2','TubeWidth_mm', ...
    'TubeThickness_mm','TubeQuantity','TubeLength_mm','FinWidth_mm', ...
    'FinHeight_mm','FinPitch_mm','FinQuantity','FinLength_mm'};
end

function names = propulsion_radiator_columns()
names = {'Radiator','Application','CoreHeight_mm','CoreWidth_mm', ...
    'FrontalArea_m2','TubeWidth_mm','TubeThickness_mm','TubeQuantity', ...
    'TubeLength_mm','FinWidth_mm','FinHeight_mm','FinPitch_mm', ...
    'FinQuantity','FinLength_mm'};
end
