function validate_system_config(cfg)
%VALIDATE_SYSTEM_CONFIG Fail early when required calculation inputs are missing or invalid.

requiredTopLevel = {'project','cycles','vehicle','motorHeat','motorCooling', ...
    'batteryCooling','cabinCooling'};
for i = 1:numel(requiredTopLevel)
    assert(isfield(cfg,requiredTopLevel{i}), ...
        'EVThermal:MissingConfiguration','Missing cfg.%s.',requiredTopLevel{i});
end

assert(cfg.vehicle.mass_kg>0,'EVThermal:InvalidVehicle','Vehicle mass must be positive.');
assert(cfg.vehicle.wheelDiameter_m>0,'EVThermal:InvalidVehicle','Wheel diameter must be positive.');
assert(cfg.vehicle.gearRatio>0,'EVThermal:InvalidVehicle','Gear ratio must be positive.');
assert(cfg.batteryCooling.capacity_Ah>0 && cfg.batteryCooling.seriesCells>=1, ...
    'EVThermal:InvalidBattery','Battery capacity and series-cell count must be positive.');
assert(cfg.batteryCooling.resistanceProxy_Ohm>=0, ...
    'EVThermal:InvalidBattery','Battery resistance proxy cannot be negative.');
assert(cfg.motorCooling.thermal.designFlow_Lmin>0 && ...
    cfg.motorCooling.thermal.hoseID_m>0, ...
    'EVThermal:InvalidCooling','Coolant flow and hose diameter must be positive.');
assert(height(cfg.motorCooling.coolant)>=1 && ...
    all(cfg.motorCooling.coolant.Density_kgm3>0) && ...
    all(cfg.motorCooling.coolant.Viscosity_Pas>0) && ...
    all(cfg.motorCooling.coolant.Cp_JkgK>0), ...
    'EVThermal:InvalidCoolant','Coolant-property table contains invalid values.');
assert(height(cfg.cycles)>=1,'EVThermal:MissingCycle','At least one drive cycle is required.');
validate_table_columns(cfg.cycles,{'Name','FileStem','File'},'cfg.cycles');
validate_table_columns(cfg.motorHeat.operatingCases, ...
    {'Name','FileStem','Speed_kmh','Grade_pct','Duration_s','Ambient_C','FanOnly'}, ...
    'cfg.motorHeat.operatingCases');

loop = cfg.motorCooling.loop;
pump = cfg.motorCooling.pump;
coolant = cfg.motorCooling.coolant;
assert(numel(loop.names)==numel(loop.length_m) && ...
    numel(loop.names)==numel(loop.bends90) && ...
    numel(loop.names)==numel(loop.returns180) && ...
    numel(loop.names)==numel(loop.teesLine) && ...
    numel(loop.names)==numel(loop.isExternalHose), ...
    'EVThermal:InvalidCoolingLoop', ...
    'Cooling-loop segment arrays must have equal length.');
assert(numel(loop.componentNames)==numel(loop.componentDrop_kPa_atReference), ...
    'EVThermal:InvalidCoolingLoop', ...
    'Component names and pressure-drop arrays must have equal length.');
assert(any(loop.flowCases_Lmin==loop.nominalFlow_Lmin), ...
    'EVThermal:InvalidCoolingLoop', ...
    'Nominal flow must be included in flowCases_Lmin.');
assert(any(loop.flowCases_Lmin==pump.referenceFlow_Lmin), ...
    'EVThermal:InvalidCoolingLoop', ...
    'Pump reference flow must be included in flowCases_Lmin.');
assert(any(coolant.Temperature_C==pump.checkTemperature_C), ...
    'EVThermal:InvalidCoolingLoop', ...
    'Pump check temperature must be included in cfg.motorCooling.coolant.');

assert(cfg.cabinCooling.designAmbient_C>=cfg.cabinCooling.cabinSetpoint_C, ...
    'EVThermal:InvalidCabinBoundary', ...
    'Cabin design ambient must not be below the cooling setpoint.');
assert(cfg.batteryCooling.regenChargeCutoff_C< ...
    cfg.batteryCooling.absoluteOperatingLimit_C, ...
    'EVThermal:InvalidBatteryLimit', ...
    'Regen cutoff must be below the absolute cell-temperature limit.');
assert(cfg.motorCooling.transient.motorThermalCapacity_JK>0 && ...
    cfg.motorCooling.transient.coolantThermalCapacity_JK>0 && ...
    cfg.motorCooling.transient.motorToCoolantResistance_KW>0 && ...
    cfg.motorCooling.transient.radiatorUA_WK>0 && ...
    cfg.motorCooling.transient.fanOnlyRadiatorUA_WK>0, ...
    'EVThermal:InvalidTransientModel', ...
    'Transient thermal capacitances, resistance and radiator UA must be positive.');

% Only files consumed by calculations are runtime requirements. Archived source
% documents are provenance references and must not prevent a reproducible run.
paths = [ ...
    string(cfg.project.parameterRegister); ...
    struct_file_paths(cfg.motorHeat.files); ...
    struct_file_paths(cfg.motorCooling.files); ...
    struct_file_paths(cfg.cabinCooling.files)];
for i = 1:numel(paths)
    assert(isfile(paths(i)),'EVThermal:MissingInputFile', ...
        'Required input file not found: %s',paths(i));
end
assert(all(isfile(cfg.cycles.File)),'EVThermal:MissingCycle', ...
    'One or more drive-cycle files are missing.');
end

function paths = struct_file_paths(files)
names = fieldnames(files);
paths = strings(numel(names),1);
for i = 1:numel(names)
    paths(i) = string(files.(names{i}));
end
end
