function validate_system_config(cfg)
%VALIDATE_SYSTEM_CONFIG Fail early when required inputs are missing or invalid.

requiredTopLevel = {'project','files','cycles','vehicle','battery','coolant', ...
    'propulsionCooling','coolingLoop','pump','hvac'};
for i = 1:numel(requiredTopLevel)
    assert(isfield(cfg,requiredTopLevel{i}), ...
        'EVThermal:MissingConfiguration','Missing cfg.%s.',requiredTopLevel{i});
end

assert(cfg.vehicle.mass_kg>0,'EVThermal:InvalidVehicle','Vehicle mass must be positive.');
assert(cfg.vehicle.wheelDiameter_m>0,'EVThermal:InvalidVehicle','Wheel diameter must be positive.');
assert(cfg.vehicle.gearRatio>0,'EVThermal:InvalidVehicle','Gear ratio must be positive.');
assert(cfg.battery.capacity_Ah>0 && cfg.battery.seriesCells>=1, ...
    'EVThermal:InvalidBattery','Battery capacity and series-cell count must be positive.');
assert(cfg.battery.resistanceProxy_Ohm>=0, ...
    'EVThermal:InvalidBattery','Battery resistance proxy cannot be negative.');
assert(cfg.propulsionCooling.designFlow_Lmin>0 && cfg.propulsionCooling.hoseID_m>0, ...
    'EVThermal:InvalidCooling','Coolant flow and hose diameter must be positive.');
assert(height(cfg.coolant)>=1 && all(cfg.coolant.Density_kgm3>0) && ...
    all(cfg.coolant.Viscosity_Pas>0) && all(cfg.coolant.Cp_JkgK>0), ...
    'EVThermal:InvalidCoolant','Coolant-property table contains invalid values.');
assert(height(cfg.cycles)>=1,'EVThermal:MissingCycle','At least one drive cycle is required.');
validate_table_columns(cfg.cycles,{'Name','FileStem','File'},'cfg.cycles');
assert(numel(cfg.coolingLoop.names)==numel(cfg.coolingLoop.length_m) && ...
    numel(cfg.coolingLoop.names)==numel(cfg.coolingLoop.bends90) && ...
    numel(cfg.coolingLoop.names)==numel(cfg.coolingLoop.returns180) && ...
    numel(cfg.coolingLoop.names)==numel(cfg.coolingLoop.teesLine) && ...
    numel(cfg.coolingLoop.names)==numel(cfg.coolingLoop.isExternalHose), ...
    'EVThermal:InvalidCoolingLoop', ...
    'Cooling-loop segment arrays must have equal length.');
assert(numel(cfg.coolingLoop.componentNames)== ...
    numel(cfg.coolingLoop.componentDrop_kPa_atReference), ...
    'EVThermal:InvalidCoolingLoop', ...
    'Component names and pressure-drop arrays must have equal length.');
assert(any(cfg.coolingLoop.flowCases_Lmin==cfg.coolingLoop.nominalFlow_Lmin), ...
    'EVThermal:InvalidCoolingLoop', ...
    'Nominal flow must be included in flowCases_Lmin.');
assert(any(cfg.coolingLoop.flowCases_Lmin==cfg.pump.referenceFlow_Lmin), ...
    'EVThermal:InvalidCoolingLoop', ...
    'Pump reference flow must be included in flowCases_Lmin.');
assert(any(cfg.coolant.Temperature_C==cfg.pump.checkTemperature_C), ...
    'EVThermal:InvalidCoolingLoop', ...
    'Pump check temperature must be included in cfg.coolant.Temperature_C.');

fileFields = fieldnames(cfg.files);
for i = 1:numel(fileFields)
    path = cfg.files.(fileFields{i});
    assert(isfile(path),'EVThermal:MissingInputFile', ...
        'Required input file not found: %s',path);
end
assert(all(isfile(cfg.cycles.File)),'EVThermal:MissingCycle', ...
    'One or more drive-cycle files are missing.');
end
