function modelFile = build_battery_requirements_simulink(cfg,options)
%BUILD_BATTERY_REQUIREMENTS_SIMULINK Build the battery requirements screen.
% The generated model implements the same central sustained equations as
% calculate_battery_requirements_screen (DC Joule heat plus peak entropic
% heat across the corrected cell-to-coolant path). It contains no transient cell,
% coolant-flow, radiator, compressor or refrigeration model.

arguments
    cfg (1,1) struct = setup_project()
    options.Overwrite (1,1) logical = false
end

if isempty(ver('simulink'))
    error('EVThermal:SimulinkRequired', ...
        'Simulink is required to generate the battery requirements screen.');
end

rootDir = cfg.project.rootDir;
modelDir = fullfile(rootDir,'models','battery_requirements');
modelName = "battery_requirements_screen";
modelFile = fullfile(modelDir,modelName+".slx");

if isfile(modelFile) && ~options.Overwrite
    error('EVThermal:ModelExists', ...
        ['Model already exists: %s\nUse Overwrite=true only when the ' ...
         'generated model should be replaced.'],modelFile);
end
if isfile(modelFile) && options.Overwrite
    delete(modelFile);
end
if bdIsLoaded(modelName)
    close_system(modelName,0);
end

new_system(modelName,'Model');
cleanup = onCleanup(@() close_if_loaded(modelName)); %#ok<NASGU>
load_system(modelName);

set_param(modelName, ...
    'SolverType','Fixed-step', ...
    'Solver','FixedStepDiscrete', ...
    'FixedStep','1', ...
    'StopTime','1');

p = cfg.batteryCooling;

add_block('simulink/Ports & Subsystems/In1', ...
    modelName+'/Sustained C-rate input','Position',[30 168 60 182]);
add_block('simulink/Math Operations/Gain', ...
    modelName+'/Convert C-rate to pack current', ...
    'Gain',number(p.capacity_Ah),'Position',[100 150 210 200]);
add_block('simulink/Math Operations/Product', ...
    modelName+'/Square pack current','Inputs','**', ...
    'Position',[255 155 300 195]);
add_block('simulink/Math Operations/Gain', ...
    modelName+'/Calculate cell DC Joule heat', ...
    'Gain',number(p.dcResistance25_Ohm), ...
    'Position',[345 145 475 205]);
add_block('simulink/Math Operations/Gain', ...
    modelName+'/Calculate peak entropic heat', ...
    'Gain',number((p.entropicReferenceTemperature_C+273.15)*p.entropicPeak_VK), ...
    'Position',[345 25 475 75]);
add_block('simulink/Math Operations/Sum', ...
    modelName+'/Add Joule and entropic heat', ...
    'Inputs','++','Position',[500 110 530 150]);
add_block('simulink/Math Operations/Gain', ...
    modelName+'/Convert cell heat to pack kW', ...
    'Gain',number(p.seriesCells/1000), ...
    'Position',[530 65 650 115]);
add_block('simulink/Math Operations/Gain', ...
    modelName+'/Calculate required temperature difference', ...
    'Gain',number(p.cellToCoolantResistance_KW), ...
    'Position',[530 225 680 275]);

add_block('simulink/Sources/Constant', ...
    modelName+'/Charge cutoff temperature limit', ...
    'Value',number(p.regenChargeCutoff_C), ...
    'Position',[735 175 785 205]);
add_block('simulink/Sources/Constant', ...
    modelName+'/Absolute cell temperature limit', ...
    'Value',number(p.absoluteOperatingLimit_C), ...
    'Position',[735 325 785 355]);
add_block('simulink/Math Operations/Sum', ...
    modelName+'/Calculate max coolant temperature for charging', ...
    'Inputs','+-','Position',[840 185 875 225]);
add_block('simulink/Math Operations/Sum', ...
    modelName+'/Calculate max coolant temperature for discharge', ...
    'Inputs','+-','Position',[840 305 875 345]);

add_outport(modelName,'Pack current output A',[255 25 285 39],1);
add_outport(modelName,'Cell heat output W',[530 145 560 159],2);
add_outport(modelName,'Pack heat output kW',[710 83 740 97],3);
add_outport(modelName,'Required temperature difference output C',[735 245 765 259],4);
add_outport(modelName,'Max coolant temperature charge output C',[940 193 970 207],5);
add_outport(modelName,'Max coolant temperature discharge output C',[940 313 970 327],6);

add_line(modelName,'Sustained C-rate input/1', ...
    'Convert C-rate to pack current/1');
add_line(modelName,'Convert C-rate to pack current/1', ...
    'Square pack current/1');
add_line(modelName,'Convert C-rate to pack current/1', ...
    'Square pack current/2');
add_line(modelName,'Convert C-rate to pack current/1', ...
    'Pack current output A/1');
add_line(modelName,'Square pack current/1', ...
    'Calculate cell DC Joule heat/1');
add_line(modelName,'Convert C-rate to pack current/1', ...
    'Calculate peak entropic heat/1');
add_line(modelName,'Calculate cell DC Joule heat/1', ...
    'Add Joule and entropic heat/1');
add_line(modelName,'Calculate peak entropic heat/1', ...
    'Add Joule and entropic heat/2');
add_line(modelName,'Add Joule and entropic heat/1', ...
    'Cell heat output W/1');
add_line(modelName,'Add Joule and entropic heat/1', ...
    'Convert cell heat to pack kW/1');
add_line(modelName,'Add Joule and entropic heat/1', ...
    'Calculate required temperature difference/1');
add_line(modelName,'Convert cell heat to pack kW/1', ...
    'Pack heat output kW/1');
add_line(modelName,'Calculate required temperature difference/1', ...
    'Required temperature difference output C/1');
add_line(modelName,'Charge cutoff temperature limit/1', ...
    'Calculate max coolant temperature for charging/1');
add_line(modelName,'Calculate required temperature difference/1', ...
    'Calculate max coolant temperature for charging/2');
add_line(modelName,'Absolute cell temperature limit/1', ...
    'Calculate max coolant temperature for discharge/1');
add_line(modelName,'Calculate required temperature difference/1', ...
    'Calculate max coolant temperature for discharge/2');
add_line(modelName,'Calculate max coolant temperature for charging/1', ...
    'Max coolant temperature charge output C/1');
add_line(modelName,'Calculate max coolant temperature for discharge/1', ...
    'Max coolant temperature discharge output C/1');

annotation = sprintf([ ...
    'SUSTAINED REQUIREMENTS SCREEN, CENTRAL ESTIMATE\n' ...
    'DC resistance %.3f mOhm = 0.40 mOhm ACR / 0.7 at 25 C.\n' ...
    'Entropic heat uses the low-SOC peak; path %.3f K/W is a bottom-cooling build-up.\n' ...
    'Ranges and sources: data/literature/literature_assumption_register.csv.'], ...
    1000*p.dcResistance25_Ohm,p.cellToCoolantResistance_KW);
note = Simulink.Annotation(modelName,annotation);
note.Position = [30 390 650 475];

Simulink.BlockDiagram.arrangeSystem(modelName);
save_system(modelName,modelFile);
close_system(modelName,0);
end

function add_outport(modelName,name,position,portNumber)
add_block('simulink/Ports & Subsystems/Out1',modelName+"/"+string(name), ...
    'Port',num2str(portNumber),'Position',position);
end

function value = number(value)
value = sprintf('%.15g',value);
end

function close_if_loaded(modelName)
if bdIsLoaded(modelName)
    close_system(modelName,0);
end
end
