function motorHeat = motor_heat_config(rootDir)
%MOTOR_HEAT_CONFIG Inputs used only to calculate integrated drive-unit heat.

arguments
    rootDir (1,1) string
end

motorHeat.files.driveLimitWorkbook = fullfile(rootDir,"data", ...
    "motor_heat","drive_unit_limits.xlsx");
motorHeat.files.driveEfficiencyMap = fullfile(rootDir,"data", ...
    "motor_heat","drive_unit_efficiency_map.csv");
motorHeat.mapBoundary = ...
    "Integrated motor/inverter/reducer map digitized from the 125 kW source chart";

% Explicit hot-weather operating cases. These are screening cases, not
% standard regulatory schedules or measured proving-ground events.
motorHeat.operatingCases = table( ...
    ["Sustained 10% grade";"Low-speed hot-weather grade"], ...
    ["sustained_grade";"low_speed_hot_weather"], ...
    [40;15],[10;5],[1200;1800],[45;45],[false;true], ...
    'VariableNames',{'Name','FileStem','Speed_kmh','Grade_pct', ...
    'Duration_s','Ambient_C','FanOnly'});
end
