function motorHeat = motor_heat_config(rootDir)
%MOTOR_HEAT_CONFIG Inputs used only to calculate integrated drive-unit heat.

arguments
    rootDir (1,1) string
end

motorHeat.files.driveLimitWorkbook = fullfile(rootDir,"data", ...
    "motor_heat","drive_unit_limits.xlsx");
motorHeat.files.driveEfficiencyMap = fullfile(rootDir,"data", ...
    "motor_heat","drive_unit_efficiency_map.csv");
motorHeat.files.controllerLossReference = fullfile(rootDir,"data", ...
    "motor_heat","controller_loss_reference.csv");
motorHeat.mapBoundary = ...
    "Integrated motor/inverter/reducer map digitized from the 125 kW source chart";

% Explicit hot-weather operating cases. These are screening cases, not
% standard regulatory schedules or measured proving-ground events.
% The third case is archived project load case L6 (8% continuous gradient,
% full load, 61.52 kW at the wheel). The 1950 kg test mass is laden (project
% owner), so no payload is added; the speed is solved from the road-load
% model so the wheel power matches L6 at 1950 kg. Its duration is assumed.
motorHeat.operatingCases = table( ...
    ["Sustained 10% grade";"Low-speed hot-weather grade"; ...
     "Project L6: 8% continuous grade, laden"], ...
    ["sustained_grade";"low_speed_hot_weather";"project_l6_continuous_grade"], ...
    [40;15;93.32079],[10;5;8],[1200;1800;1200],[45;45;45],[false;true;false], ...
    [0;0;0], ...
    'VariableNames',{'Name','FileStem','Speed_kmh','Grade_pct', ...
    'Duration_s','Ambient_C','FanOnly','ExtraMass_kg'});
end
