function out = run_cooling_loop_analysis(cfg)
%RUN_COOLING_LOOP_ANALYSIS Propulsion-loop hydraulic sensitivity.

g = cfg.coolingLoop;
c = cfg.coolant;
flows = g.flowCases_Lmin;
summaryTables = cell(height(c),1);

for j=1:height(c)
    local = cell(numel(flows),1);
    for i=1:numel(flows)
        [segments,summary] = calculate_cooling_loop_losses(g,flows(i),c.Density_kgm3(j),c.Viscosity_Pas(j));
        summary.CoolantCase = repmat(string(sprintf('%d C',c.Temperature_C(j))),height(summary),1);
        summary.Temperature_C = repmat(c.Temperature_C(j),height(summary),1);
        local{i}=summary;
        if c.Temperature_C(j)==g.nominalTemperature_C && ...
                flows(i)==g.nominalFlow_Lmin
            out.nominalSegments=segments;
        end
    end
    summaryTables{j}=vertcat(local{:});
end
out.sensitivity=vertcat(summaryTables{:});

% Compare the configured pump point at the representative hot-loop coolant
% temperature. Colder rows remain visible as sensitivity results, but they do
% not define the normal operating-point verdict.
pumpFlow = cfg.pump.referenceFlow_Lmin;
pumpHead = cfg.pump.minimumHead_kPa;
pumpTemperature = cfg.pump.checkTemperature_C;
pumpRows = out.sensitivity(out.sensitivity.Flow_Lmin==pumpFlow & ...
    out.sensitivity.Temperature_C==pumpTemperature,:);
if height(pumpRows)~=1
    error('EVThermal:MissingPumpCheckCase', ...
        'One hydraulic result is required at %.1f L/min and %.1f C.', ...
        pumpFlow,pumpTemperature);
end
pumpRow = pumpRows(1,:);
out.pumpCheck = table(pumpFlow,pumpHead,pumpRow.Temperature_C, ...
    pumpRow.ExternalHoseMajorLoss_kPa,pumpRow.ExternalFittingMinorLoss_kPa, ...
    pumpRow.KnownComponentAllowance_kPa, ...
    pumpRow.EvidenceBackedPartialSubtotal_kPa, ...
    pumpRow.IllustrativeSubtotalIncludingRadiatorRoute_kPa, ...
    pumpHead-pumpRow.EvidenceBackedPartialSubtotal_kPa, ...
    pumpHead>=pumpRow.EvidenceBackedPartialSubtotal_kPa, ...
    "Full active pump curve required for final confirmation", ...
    'VariableNames',{'SpecifiedFlow_Lmin','SpecifiedMinimumHead_kPa', ...
    'OperatingCoolantTemperature_C','ExternalHoseMajorLoss_kPa', ...
    'ExternalFittingMinorLoss_kPa','KnownComponentAllowance_kPa', ...
    'EvidenceBackedPartialLoop_kPa','IllustrativeLoopIncludingRadiatorRoute_kPa', ...
    'MinimumDocumentedHeadMargin_kPa','DocumentedPointCoversPartialLoop', ...
    'Conclusion'});
out.inactivePumpCurve = read_project_csv(cfg.files.inactivePumpCurve, ...
    {'Flow_Lmin','Flow_Lh','InactivePumpResistance_kPa', ...
     'DigitizationUncertainty_kPa','EvidenceStatus'}, ...
    {'Flow_Lmin','Flow_Lh','InactivePumpResistance_kPa', ...
     'DigitizationUncertainty_kPa'});
out.inactivePumpCases = table([g.nominalFlow_Lmin;pumpFlow], ...
    [interpolate_inactive_pump_resistance(out.inactivePumpCurve,g.nominalFlow_Lmin); ...
     interpolate_inactive_pump_resistance(out.inactivePumpCurve,pumpFlow)], ...
    repmat("Inactive-pump series-flow scenario only; not active pump head",2,1), ...
    'VariableNames',{'Flow_Lmin','InactivePumpResistance_kPa','Interpretation'});

writetable(out.nominalSegments,fullfile(cfg.project.outputDir,'cooling_loop_segment_results.csv'));
writetable(out.sensitivity,fullfile(cfg.project.outputDir,'cooling_loop_sensitivity_results.csv'));
writetable(out.inactivePumpCases,fullfile(cfg.project.outputDir,'inactive_pump_resistance_cases.csv'));
writetable(out.pumpCheck,fullfile(cfg.project.outputDir,'pump_operating_point_check.csv'));

fig=figure('Visible','off','Color','w'); hold on;
for j=1:height(c)
    rows=out.sensitivity.Temperature_C==c.Temperature_C(j);
    plot(out.sensitivity.Flow_Lmin(rows),out.sensitivity.IllustrativeSubtotalIncludingRadiatorRoute_kPa(rows),'o-','LineWidth',1.5);
end
grid on; xlabel('Coolant flow (L/min)'); ylabel('Illustrative known subtotal (kPa)');
legend('20 C','40 C','60 C','Location','northwest');
exportgraphics(fig,fullfile(cfg.project.outputDir,'cooling_loop_sensitivity.png'),'Resolution',180); close(fig);
end
