function result = calculate_radiator_design_requirements( ...
    caseNames,heatDuty_kW,thermal,coolant,coreArea_m2)
%CALCULATE_RADIATOR_DESIGN_REQUIREMENTS First-pass radiator and airflow duty.
% The result sizes required heat rejection, air flow and ideal counterflow UA.
% It does not predict fan delivery, ram-air capture or achieved core UA.

arguments
    caseNames string
    heatDuty_kW double {mustBeNonnegative}
    thermal (1,1) struct
    coolant table
    coreArea_m2 (1,1) double {mustBePositive}
end

caseNames = caseNames(:);
heatDuty_kW = heatDuty_kW(:);
assert(height(coolant)==1 && ...
    all(ismember({'Density_kgm3','Cp_JkgK'}, ...
    coolant.Properties.VariableNames)), ...
    'EVThermal:RadiatorCoolantInput', ...
    'Coolant input must contain one row with density and specific heat.');
assert(numel(caseNames)==numel(heatDuty_kW), ...
    'EVThermal:RadiatorInputSize', ...
    'Case and heat-duty vectors must have equal length.');

q_W = heatDuty_kW*1000;
coolantMassFlow_kgs = thermal.designFlow_Lmin/60000*coolant.Density_kgm3;
coolantOut_C = thermal.radiatorCoolantIn_C- ...
    q_W/(coolantMassFlow_kgs*coolant.Cp_JkgK);

hotEndDifference_C = thermal.radiatorCoolantIn_C-thermal.airOut_C;
coldEndDifference_C = coolantOut_C-thermal.airIn_C;
boundaryFeasible = hotEndDifference_C>0 & coldEndDifference_C>0;
lmtd_C = nan(size(q_W));
for i = 1:numel(q_W)
    if boundaryFeasible(i)
        if abs(coldEndDifference_C(i)-hotEndDifference_C)<1e-10
            lmtd_C(i) = hotEndDifference_C;
        else
            lmtd_C(i) = (coldEndDifference_C(i)-hotEndDifference_C)/ ...
                log(coldEndDifference_C(i)/hotEndDifference_C);
        end
    end
end
requiredUA_WK = q_W./lmtd_C;

airDensity_kgm3 = thermal.ambientPressure_Pa/( ...
    thermal.airGasConstant_JkgK*(thermal.airIn_C+273.15));
requiredAirMassFlow_kgs = q_W/(thermal.airCp_JkgK* ...
    (thermal.airOut_C-thermal.airIn_C));
requiredAirVolumeFlow_m3s = requiredAirMassFlow_kgs/airDensity_kgm3;
requiredCoreFaceVelocity_ms = requiredAirVolumeFlow_m3s/coreArea_m2;

result = table(caseNames,heatDuty_kW, ...
    repmat(thermal.designFlow_Lmin,numel(q_W),1),coolantOut_C, ...
    lmtd_C,requiredUA_WK,requiredAirMassFlow_kgs, ...
    requiredAirVolumeFlow_m3s,requiredCoreFaceVelocity_ms, ...
    repmat(thermal.airOut_C-thermal.airIn_C,numel(q_W),1), ...
    boundaryFeasible, ...
    'VariableNames',{'Case','SustainedHeatDuty_kW', ...
    'CoolantFlow_Lmin','CalculatedRadiatorCoolantOut_C','IdealLMTD_C', ...
    'RequiredIdealUA_WK','RequiredAirMassFlow_kgs', ...
    'RequiredAirVolumeFlow_m3s','RequiredCoreFaceVelocity_ms', ...
    'AssumedAirTemperatureRise_C', ...
    'TemperatureBoundaryFeasible'});
end
