function summary = summarize_battery_cooling(result,battery)
%SUMMARIZE_BATTERY_COOLING Time-weighted battery heat and cooling response.

duration_s = result.Time_s(end)-result.Time_s(1);
heatEnergy_kWh = trapz(result.Time_s,result.BatteryHeat_kW)/3600;
[peakHeat_kW,peakHeatIndex] = max(result.BatteryHeat_kW);
[peakTemperature_C,peakTemperatureIndex] = ...
    max(result.EstimatedCellTemperature_C);
[minimumTemperature_C,minimumTemperatureIndex] = ...
    min(result.EstimatedCellTemperature_C);
coolingEnergy_kWh = ...
    trapz(result.Time_s,result.BatteryCoolingRequest_kW)/3600;
averageCoolingRequest_kW = coolingEnergy_kWh*3600/duration_s;
coolingActiveTime_pct = 100*trapz(result.Time_s, ...
    double(result.BatteryCoolingActive))/duration_s;
storedThermalEnergyChange_kWh = battery.seriesCells* ...
    battery.cellMass_kg*battery.cellCp_JkgK* ...
    (result.EstimatedCellTemperature_C(end)- ...
     result.EstimatedCellTemperature_C(1))/3.6e6;

summary = table(result.Cycle(1),duration_s, ...
    heatEnergy_kWh*3600/duration_s,peakHeat_kW, ...
    result.Time_s(peakHeatIndex),heatEnergy_kWh, ...
    max(abs(result.PackCurrent_A)), ...
    result.EstimatedCellTemperature_C(1), ...
    result.EstimatedCellTemperature_C(end), ...
    minimumTemperature_C,result.Time_s(minimumTemperatureIndex), ...
    peakTemperature_C,result.Time_s(peakTemperatureIndex), ...
    battery.maximumCell_C-peakTemperature_C, ...
    averageCoolingRequest_kW,max(result.BatteryCoolingRequest_kW), ...
    coolingEnergy_kWh,coolingActiveTime_pct,storedThermalEnergyChange_kWh, ...
    all(result.EstimatedCellTemperature_C<=battery.maximumCell_C), ...
    'VariableNames',{'Cycle','Duration_s','AverageBatteryHeat_kW', ...
    'PeakBatteryHeat_kW','PeakBatteryHeatTime_s','BatteryHeatEnergy_kWh', ...
    'PeakAbsolutePackCurrent_A','InitialCellTemperature_C', ...
    'FinalCellTemperature_C','MinimumCellTemperature_C', ...
    'MinimumCellTemperatureTime_s','PeakEstimatedCellTemperature_C', ...
    'PeakCellTemperatureTime_s','CellTemperatureMargin_C', ...
    'AverageBatteryCoolingRequest_kW','PeakBatteryCoolingRequest_kW', ...
    'BatteryCoolingEnergy_kWh','CoolingActiveTime_pct', ...
    'StoredThermalEnergyChange_kWh','CellTemperatureWithinLimit'});
end
