function summary = summarize_drive_cycle(result)
%SUMMARIZE_DRIVE_CYCLE Headline average, peak and energy values.
% Energy is integrated with the actual time vector. Average power is then
% energy divided by elapsed time, which remains correct for unequal time steps.

name = result.Cycle(1);
duration_s = result.Time_s(end)-result.Time_s(1);
distance_km = trapz(result.Time_s,result.Speed_ms)/1000;
driveHeatEnergy_kWh = trapz(result.Time_s,result.DriveUnitHeat_kW)/3600;
batteryHeatEnergy_kWh = trapz(result.Time_s,result.BatteryHeat_kW)/3600;
averageDriveHeat_kW = driveHeatEnergy_kWh*3600/duration_s;
averageBatteryHeat_kW = batteryHeatEnergy_kWh*3600/duration_s;
summary = table(name,duration_s,distance_km,max(result.Speed_mph), ...
    averageDriveHeat_kW,max(result.DriveUnitHeat_kW),driveHeatEnergy_kWh, ...
    averageBatteryHeat_kW,max(result.BatteryHeat_kW),batteryHeatEnergy_kWh, ...
    max(abs(result.PackCurrent_A)),max(result.MotorSpeed_rpm), ...
    max(result.EstimatedCellTemperature_C), ...
    all(result.TorqueWithinCurve),all(result.PowerWithinCurve), ...
    'VariableNames',{'Cycle','Duration_s','Distance_km','MaximumSpeed_mph', ...
    'AverageDriveUnitHeat_kW','PeakDriveUnitHeat_kW','DriveUnitHeatEnergy_kWh', ...
    'AverageBatteryHeat_kW','PeakBatteryHeat_kW','BatteryHeatEnergy_kWh', ...
    'PeakAbsolutePackCurrent_A','PeakMotorSpeed_rpm','PeakEstimatedCellTemperature_C', ...
    'TorqueTraceFeasible','PowerTraceFeasible'});
end
