function summary = summarize_battery_cooling(result,battery)
%SUMMARIZE_BATTERY_COOLING Time-weighted battery heat and cooling response.

duration_s = result.Time_s(end)-result.Time_s(1);
heatEnergy_kWh = trapz(result.Time_s,result.BatteryHeat_kW)/3600;
summary = table(result.Cycle(1),duration_s, ...
    heatEnergy_kWh*3600/duration_s,max(result.BatteryHeat_kW), ...
    heatEnergy_kWh,max(abs(result.PackCurrent_A)), ...
    max(result.EstimatedCellTemperature_C), ...
    max(result.BatteryCoolingRequest_kW), ...
    all(result.EstimatedCellTemperature_C<=battery.maximumCell_C), ...
    'VariableNames',{'Cycle','Duration_s','AverageBatteryHeat_kW', ...
    'PeakBatteryHeat_kW','BatteryHeatEnergy_kWh', ...
    'PeakAbsolutePackCurrent_A','PeakEstimatedCellTemperature_C', ...
    'PeakBatteryCoolingRequest_kW','CellTemperatureWithinLimit'});
end
