function summary = summarize_motor_heat(result)
%SUMMARIZE_MOTOR_HEAT Time-weighted drive-unit heat results for one cycle.

duration_s = result.Time_s(end)-result.Time_s(1);
heatEnergy_kWh = trapz(result.Time_s,result.DriveUnitHeat_kW)/3600;
summary = table(result.Cycle(1),duration_s, ...
    trapz(result.Time_s,result.Speed_ms)/1000,max(result.Speed_mph), ...
    heatEnergy_kWh*3600/duration_s,max(result.DriveUnitHeat_kW), ...
    heatEnergy_kWh,max(result.MotorSpeed_rpm), ...
    all(result.TorqueWithinCurve),all(result.PowerWithinCurve), ...
    'VariableNames',{'Cycle','Duration_s','Distance_km','MaximumSpeed_mph', ...
    'AverageDriveUnitHeat_kW','PeakDriveUnitHeat_kW', ...
    'DriveUnitHeatEnergy_kWh','PeakMotorSpeed_rpm', ...
    'TorqueTraceFeasible','PowerTraceFeasible'});
end
