function out = run_motor_cooling(cfg,motorHeat)
%RUN_MOTOR_COOLING Transient propulsion thermal and hydraulic screens.

p = cfg.motorCooling.transient;
c = cfg.motorCooling.coolant;
g = cfg.motorCooling.loop;
pump = cfg.motorCooling.pump;
outputDir = fullfile(cfg.project.outputDir,"motor_cooling");
ensure_output_folder(outputDir);

nCases = numel(motorHeat.details);
out.details = cell(nCases,1);
summaries = cell(nCases,1);
for i = 1:nCases
    caseParameters = p;
    if motorHeat.fanOnly(i)
        caseParameters.radiatorUA_WK = p.fanOnlyRadiatorUA_WK;
    end
    out.details{i} = simulate_motor_coolant_thermal( ...
        motorHeat.details{i},motorHeat.ambient_C(i),caseParameters);
    summaries{i} = summarize_thermal_case(out.details{i},caseParameters);
    writetable(out.details{i},fullfile(outputDir, ...
        motorHeat.fileStems(i)+"_motor_thermal_trace.csv"));
end
out.summary = vertcat(summaries{:});
out.hydraulics = evaluate_hydraulics(g,c,pump, ...
    cfg.motorCooling.files.inactivePumpCurve);

writetable(out.summary,fullfile(outputDir,"motor_thermal_summary.csv"));
writetable(out.hydraulics.nominalSegments, ...
    fullfile(outputDir,"loop_segments.csv"));
writetable(out.hydraulics.sensitivity, ...
    fullfile(outputDir,"loop_sensitivity.csv"));
writetable(out.hydraulics.pumpCheck, ...
    fullfile(outputDir,"pump_operating_point.csv"));

plot_motor_thermal_response(out.details,p,outputDir);
plot_hydraulic_sensitivity(out.hydraulics.sensitivity,c,pump,outputDir);
end

function summary = summarize_thermal_case(trace,p)
duration_s = trace.Time_s(end)-trace.Time_s(1);
generated_kWh = trapz(trace.Time_s,trace.DriveUnitHeat_kW)/3600;
rejected_kWh = trapz(trace.Time_s,trace.RadiatorHeatRejection_kW)/3600;
stored_kWh = ( ...
    p.motorThermalCapacity_JK*(trace.MotorTemperature_C(end)- ...
        trace.MotorTemperature_C(1))+ ...
    p.coolantThermalCapacity_JK*(trace.CoolantTemperature_C(end)- ...
        trace.CoolantTemperature_C(1)))/3.6e6;
summary = table(trace.Case(1),duration_s,trace.Ambient_C(1), ...
    max(trace.DriveUnitHeat_kW),max(trace.MotorTemperature_C), ...
    max(trace.CoolantTemperature_C),generated_kWh,rejected_kWh,stored_kWh, ...
    generated_kWh-rejected_kWh-stored_kWh, ...
    p.motorThermalCapacity_JK,p.coolantThermalCapacity_JK, ...
    p.motorToCoolantResistance_KW,p.radiatorUA_WK,string(p.modelBoundary), ...
    'VariableNames',{'Case','Duration_s','Ambient_C','PeakHeat_kW', ...
    'PeakMotorTemperature_C','PeakCoolantTemperature_C', ...
    'GeneratedHeat_kWh','RadiatorRejectedHeat_kWh','StoredHeatChange_kWh', ...
    'EnergyBalanceResidual_kWh','AssumedMotorThermalCapacity_JK', ...
    'AssumedCoolantThermalCapacity_JK','AssumedMotorToCoolantResistance_KW', ...
    'AssumedRadiatorUA_WK','ModelBoundary'});
end

function out = evaluate_hydraulics(g,c,pump,inactivePumpCurveFile)
flows = g.flowCases_Lmin;
summaryTables = cell(height(c),1);
for j = 1:height(c)
    local = cell(numel(flows),1);
    for i = 1:numel(flows)
        [segments,summary] = calculate_cooling_loop_losses( ...
            g,flows(i),c.Density_kgm3(j),c.Viscosity_Pas(j));
        summary.CoolantCase = repmat(string(sprintf('%d C', ...
            c.Temperature_C(j))),height(summary),1);
        summary.Temperature_C = repmat(c.Temperature_C(j),height(summary),1);
        local{i} = summary;
        if c.Temperature_C(j)==g.nominalTemperature_C && ...
                flows(i)==g.nominalFlow_Lmin
            out.nominalSegments = segments;
        end
    end
    summaryTables{j} = vertcat(local{:});
end
out.sensitivity = vertcat(summaryTables{:});

pumpRows = out.sensitivity( ...
    out.sensitivity.Flow_Lmin==pump.referenceFlow_Lmin & ...
    out.sensitivity.Temperature_C==pump.checkTemperature_C,:);
if height(pumpRows)~=1
    error('EVThermal:MissingPumpCheckCase', ...
        'One result is required at %.1f L/min and %.1f C.', ...
        pump.referenceFlow_Lmin,pump.checkTemperature_C);
end
pumpRow = pumpRows(1,:);
coversPartialLoop = ...
    pump.minimumHead_kPa>=pumpRow.EvidenceBackedPartialSubtotal_kPa;
if coversPartialLoop
    conclusion = "Documented pump point covers the known partial-loop requirement";
else
    conclusion = "Documented pump point fails the known partial-loop requirement";
end
out.pumpCheck = table(pump.referenceFlow_Lmin,pump.minimumHead_kPa, ...
    pumpRow.Temperature_C,pumpRow.ExternalHoseMajorLoss_kPa, ...
    pumpRow.ExternalFittingMinorLoss_kPa, ...
    pumpRow.KnownComponentAllowance_kPa, ...
    pumpRow.EvidenceBackedPartialSubtotal_kPa, ...
    pump.minimumHead_kPa-pumpRow.EvidenceBackedPartialSubtotal_kPa, ...
    coversPartialLoop,conclusion, ...
    'VariableNames',{'SpecifiedFlow_Lmin','SpecifiedMinimumHead_kPa', ...
    'OperatingCoolantTemperature_C','ExternalHoseMajorLoss_kPa', ...
    'ExternalFittingMinorLoss_kPa','KnownComponentAllowance_kPa', ...
    'KnownPartialLoop_kPa','MinimumDocumentedHeadMargin_kPa', ...
    'DocumentedPointCoversPartialLoop','Conclusion'});

% Preserve and validate the inactive-pump source curve without including it
% in the active-loop decision.
out.inactivePumpCurve = read_project_csv(inactivePumpCurveFile, ...
    {'Flow_Lmin','Flow_Lh','InactivePumpResistance_kPa', ...
     'DigitizationUncertainty_kPa','EvidenceStatus'}, ...
    {'Flow_Lmin','Flow_Lh','InactivePumpResistance_kPa', ...
     'DigitizationUncertainty_kPa'});
end

function plot_motor_thermal_response(details,p,outputDir)
fig = figure('Visible','off','Color','w','Position',[100 100 1250 820]);
layout = tiledlayout(2,2,'TileSpacing','compact');
for i = 1:numel(details)
    nexttile;
    plot(details{i}.Time_s,details{i}.MotorTemperature_C, ...
        'LineWidth',1.4,'DisplayName','Drive unit');
    hold on;
    plot(details{i}.Time_s,details{i}.CoolantTemperature_C, ...
        'LineWidth',1.4,'DisplayName','Coolant');
    yline(details{i}.Ambient_C(1),':','Ambient','HandleVisibility','off');
    grid on;
    ylabel('Temperature (C)');
    title(details{i}.Case(1));
    legend('Location','best');
end
xlabel(layout,'Time (s)');
title(layout,sprintf(['Transient two-node screen: normal/fan-only UA ' ...
    '%.0f/%.0f W/K, R %.3f K/W'],p.radiatorUA_WK, ...
    p.fanOnlyRadiatorUA_WK,p.motorToCoolantResistance_KW));
exportgraphics(fig,fullfile(outputDir,"motor_thermal_response.png"), ...
    'Resolution',180);
close(fig);
end

function plot_hydraulic_sensitivity(sensitivity,c,pump,outputDir)
fig = figure('Visible','off','Color','w');
hold on;
labels = strings(height(c),1);
for j = 1:height(c)
    rows = sensitivity.Temperature_C==c.Temperature_C(j);
    plot(sensitivity.Flow_Lmin(rows), ...
        sensitivity.EvidenceBackedPartialSubtotal_kPa(rows), ...
        'o-','LineWidth',1.5);
    labels(j) = string(sprintf('%d C',c.Temperature_C(j)));
end
plot(pump.referenceFlow_Lmin,pump.minimumHead_kPa,'rp', ...
    'MarkerSize',13,'MarkerFaceColor','r');
labels(end+1) = "Documented pump point";
grid on;
xlabel('Coolant flow (L/min)');
ylabel('Known partial-loop pressure loss (kPa)');
legend(labels,'Location','northwest');
exportgraphics(fig,fullfile(outputDir,"loop_sensitivity.png"), ...
    'Resolution',180);
close(fig);
end

function ensure_output_folder(folder)
if ~isfolder(folder)
    mkdir(folder);
end
end
