function out = run_motor_cooling(cfg,motorHeat)
%RUN_MOTOR_COOLING Propulsion coolant transport, radiator and hydraulics.
% The only cross-domain input is the motor-heat summary produced by
% run_motor_heat_generation.

p = cfg.motorCooling.thermal;
c = cfg.motorCooling.coolant;
g = cfg.motorCooling.loop;
pump = cfg.motorCooling.pump;
files = cfg.motorCooling.files;
outputDir = fullfile(cfg.project.outputDir,"motor_cooling");
ensure_output_folder(outputDir);

nominal = c(c.Temperature_C==p.propertyTemperature_C,:);
if height(nominal)~=1
    error('EVThermal:MissingCoolantProperty', ...
        'One coolant-property row is required at %.1f C.', ...
        p.propertyTemperature_C);
end

out.heat = make_cycle_heat_table(motorHeat.summary);
out.coolant = calculate_coolant_transport(out.heat.ThermalDuty_kW, ...
    p.designFlow_Lmin,p.hoseID_m,nominal.Density_kgm3,nominal.Cp_JkgK);
out.coolant.Cycle = out.heat.Cycle;
out.coolant.LoadMetric = out.heat.LoadMetric;

radiatorCoolantOut_C = p.radiatorCoolantIn_C-out.coolant.CoolantRise_C;
out.radiator = calculate_radiator_requirement(out.heat.ThermalDuty_kW, ...
    p.radiatorCoolantIn_C,radiatorCoolantOut_C, ...
    p.airIn_C,p.airOut_C,p.airCp_JkgK);
out.radiator.Cycle = out.heat.Cycle;
out.radiator.LoadMetric = out.heat.LoadMetric;

out.thermalReference = read_project_csv(files.thermalReference, ...
    {'ReferenceCase','CoolantInlet_C','CoolantFlow_Lmin', ...
     'ReportedWindingTemperature_C','Duration_s','EvidenceStatus'}, ...
    {'CoolantInlet_C','CoolantFlow_Lmin', ...
     'ReportedWindingTemperature_C','Duration_s'});
out.radiatorGeometry = read_project_csv(files.radiatorGeometry, ...
    radiator_geometry_columns(),radiator_geometry_numeric_columns());
out.hydraulics = evaluate_hydraulics(g,c,pump,files.inactivePumpCurve);
out.currentResult = build_current_result(out.heat,out.coolant, ...
    out.radiator,out.hydraulics.pumpCheck);

writetable(out.heat,fullfile(outputDir,"motor_heat_boundary.csv"));
writetable(out.coolant,fullfile(outputDir,"coolant_transport.csv"));
writetable(out.radiator,fullfile(outputDir,"radiator_requirement.csv"));
writetable(out.thermalReference,fullfile(outputDir,"motor_thermal_reference.csv"));
writetable(out.radiatorGeometry,fullfile(outputDir,"radiator_geometry.csv"));
writetable(out.hydraulics.nominalSegments, ...
    fullfile(outputDir,"loop_segments.csv"));
writetable(out.hydraulics.sensitivity, ...
    fullfile(outputDir,"loop_sensitivity.csv"));
writetable(out.hydraulics.pumpCheck, ...
    fullfile(outputDir,"pump_operating_point.csv"));
writetable(out.hydraulics.inactivePumpCases, ...
    fullfile(outputDir,"inactive_pump_cases.csv"));
writetable(out.currentResult, ...
    fullfile(outputDir,"motor_cooling_current_result.csv"));

plot_hydraulic_sensitivity(out.hydraulics.sensitivity,c,outputDir);
plot_motor_cooling_requirements(out.currentResult,outputDir);
end

function current = build_current_result(heat,coolant,radiator,pumpCheck)
n = height(heat);
current = table(heat.Cycle,heat.LoadMetric,heat.ThermalDuty_kW, ...
    coolant.CoolantFlow_Lmin,coolant.CoolantMassFlow_kgs, ...
    coolant.CoolantRise_C,radiator.CoolantIn_C,radiator.CoolantOut_C, ...
    radiator.AssumedLMTD_K,radiator.RequiredUA_WK, ...
    radiator.RequiredAirMassFlow_kgs, ...
    repmat(pumpCheck.SpecifiedMinimumHead_kPa,n,1), ...
    repmat(pumpCheck.EvidenceBackedPartialLoop_kPa,n,1), ...
    repmat(pumpCheck.MinimumDocumentedHeadMargin_kPa,n,1), ...
    repmat(pumpCheck.DocumentedPointCoversPartialLoop,n,1), ...
    'VariableNames',{'Cycle','LoadMetric','ThermalDuty_kW', ...
    'CoolantFlow_Lmin','CoolantMassFlow_kgs','CoolantRise_C', ...
    'RadiatorCoolantIn_C','RadiatorCoolantOut_C','AssumedLMTD_K', ...
    'RequiredUA_WK','RequiredAirMassFlow_kgs', ...
    'SpecifiedMinimumPumpHead_kPa','EvidenceBackedPartialLoop_kPa', ...
    'MinimumDocumentedHeadMargin_kPa','PumpPointCoversPartialLoop'});
end

function out = evaluate_hydraulics(g,c,pump,inactivePumpCurveFile)
flows = g.flowCases_Lmin;
summaryTables = cell(height(c),1);
for j = 1:height(c)
    local = cell(numel(flows),1);
    for i = 1:numel(flows)
        [segments,summary] = calculate_cooling_loop_losses( ...
            g,flows(i),c.Density_kgm3(j),c.Viscosity_Pas(j));
        summary.CoolantCase = repmat(string(sprintf('%d C', ...
            c.Temperature_C(j))),height(summary),1);
        summary.Temperature_C = repmat(c.Temperature_C(j),height(summary),1);
        local{i} = summary;
        if c.Temperature_C(j)==g.nominalTemperature_C && ...
                flows(i)==g.nominalFlow_Lmin
            out.nominalSegments = segments;
        end
    end
    summaryTables{j} = vertcat(local{:});
end
out.sensitivity = vertcat(summaryTables{:});

pumpRows = out.sensitivity( ...
    out.sensitivity.Flow_Lmin==pump.referenceFlow_Lmin & ...
    out.sensitivity.Temperature_C==pump.checkTemperature_C,:);
if height(pumpRows)~=1
    error('EVThermal:MissingPumpCheckCase', ...
        'One result is required at %.1f L/min and %.1f C.', ...
        pump.referenceFlow_Lmin,pump.checkTemperature_C);
end
pumpRow = pumpRows(1,:);
out.pumpCheck = table(pump.referenceFlow_Lmin,pump.minimumHead_kPa, ...
    pumpRow.Temperature_C,pumpRow.ExternalHoseMajorLoss_kPa, ...
    pumpRow.ExternalFittingMinorLoss_kPa, ...
    pumpRow.KnownComponentAllowance_kPa, ...
    pumpRow.EvidenceBackedPartialSubtotal_kPa, ...
    pumpRow.IllustrativeSubtotalIncludingRadiatorRoute_kPa, ...
    pump.minimumHead_kPa-pumpRow.EvidenceBackedPartialSubtotal_kPa, ...
    pump.minimumHead_kPa>=pumpRow.EvidenceBackedPartialSubtotal_kPa, ...
    "Full active Q-H curve required for final confirmation", ...
    'VariableNames',{'SpecifiedFlow_Lmin','SpecifiedMinimumHead_kPa', ...
    'OperatingCoolantTemperature_C','ExternalHoseMajorLoss_kPa', ...
    'ExternalFittingMinorLoss_kPa','KnownComponentAllowance_kPa', ...
    'EvidenceBackedPartialLoop_kPa', ...
    'IllustrativeLoopIncludingRadiatorRoute_kPa', ...
    'MinimumDocumentedHeadMargin_kPa','DocumentedPointCoversPartialLoop', ...
    'Conclusion'});

out.inactivePumpCurve = read_project_csv(inactivePumpCurveFile, ...
    {'Flow_Lmin','Flow_Lh','InactivePumpResistance_kPa', ...
     'DigitizationUncertainty_kPa','EvidenceStatus'}, ...
    {'Flow_Lmin','Flow_Lh','InactivePumpResistance_kPa', ...
     'DigitizationUncertainty_kPa'});
out.inactivePumpCases = table([g.nominalFlow_Lmin;pump.referenceFlow_Lmin], ...
    [interpolate_inactive_pump_resistance( ...
        out.inactivePumpCurve,g.nominalFlow_Lmin); ...
     interpolate_inactive_pump_resistance( ...
        out.inactivePumpCurve,pump.referenceFlow_Lmin)], ...
    repmat("Inactive-pump series-flow scenario only; not active pump head",2,1), ...
    'VariableNames',{'Flow_Lmin','InactivePumpResistance_kPa','Interpretation'});
end

function heat = make_cycle_heat_table(summary)
n = height(summary);
heat = table(repelem(summary.Cycle,2),repmat(["Average";"Peak"],n,1), ...
    reshape([summary.AverageDriveUnitHeat_kW ...
             summary.PeakDriveUnitHeat_kW]',[],1), ...
    repmat("Configured integrated drive-unit efficiency map",2*n,1), ...
    'VariableNames',{'Cycle','LoadMetric','ThermalDuty_kW','Boundary'});
end

function plot_hydraulic_sensitivity(sensitivity,c,outputDir)
fig = figure('Visible','off','Color','w');
hold on;
labels = strings(height(c),1);
for j = 1:height(c)
    rows = sensitivity.Temperature_C==c.Temperature_C(j);
    plot(sensitivity.Flow_Lmin(rows), ...
        sensitivity.IllustrativeSubtotalIncludingRadiatorRoute_kPa(rows), ...
        'o-','LineWidth',1.5);
    labels(j) = string(sprintf('%d C',c.Temperature_C(j)));
end
grid on;
xlabel('Coolant flow (L/min)');
ylabel('Illustrative known subtotal (kPa)');
legend(labels,'Location','northwest');
exportgraphics(fig,fullfile(outputDir,"loop_sensitivity.png"), ...
    'Resolution',180);
close(fig);
end

function plot_motor_cooling_requirements(current,outputDir)
labels = current.Cycle+" "+current.LoadMetric;
fig = figure('Visible','off','Color','w','Position',[100 100 1250 800]);
layout = tiledlayout(2,2,'TileSpacing','compact');

nexttile;
bar(current.ThermalDuty_kW);
format_category_axis(labels,'Thermal duty (kW)');

nexttile;
bar(current.CoolantRise_C);
format_category_axis(labels,'Coolant rise (C)');

nexttile;
bar(current.RequiredUA_WK);
format_category_axis(labels,'Required UA (W/K)');

nexttile;
bar(current.RequiredAirMassFlow_kgs);
format_category_axis(labels,'Required air flow (kg/s)');

title(layout,'Propulsion-loop thermal requirements');
exportgraphics(fig,fullfile(outputDir,"motor_cooling_requirements.png"), ...
    'Resolution',180);
close(fig);
end

function format_category_axis(labels,yAxisLabel)
grid on;
xticks(1:numel(labels));
xticklabels(labels);
xtickangle(20);
ylabel(yAxisLabel);
end

function names = radiator_geometry_columns()
names = {'Radiator','Application','CoreHeight_mm','CoreWidth_mm', ...
    'FrontalArea_m2','TubeWidth_mm','TubeThickness_mm','TubeQuantity', ...
    'TubeLength_mm','FinWidth_mm','FinHeight_mm','FinPitch_mm', ...
    'FinQuantity','FinLength_mm'};
end

function names = radiator_geometry_numeric_columns()
names = {'CoreHeight_mm','CoreWidth_mm','FrontalArea_m2','TubeWidth_mm', ...
    'TubeThickness_mm','TubeQuantity','TubeLength_mm','FinWidth_mm', ...
    'FinHeight_mm','FinPitch_mm','FinQuantity','FinLength_mm'};
end

function ensure_output_folder(folder)
if ~isfolder(folder)
    mkdir(folder);
end
end
