function modelFile = build_battery_loop_simulink(cfg,options)
%BUILD_BATTERY_LOOP_SIMULINK Build the standalone battery requirements model.
% The generated model implements the same sustained lower-bound equations
% as calculate_battery_loop_requirements. It contains no transient cell,
% coolant-flow, radiator, compressor or refrigeration model.

arguments
    cfg (1,1) struct = setup_project()
    options.Overwrite (1,1) logical = false
end

if isempty(ver('simulink'))
    error('EVThermal:SimulinkRequired', ...
        'Simulink is required to generate the battery-loop model.');
end

rootDir = cfg.project.rootDir;
modelDir = fullfile(rootDir,'models','battery_loop');
modelName = "battery_loop_requirements";
modelFile = fullfile(modelDir,modelName+".slx");

if isfile(modelFile) && ~options.Overwrite
    error('EVThermal:ModelExists', ...
        ['Model already exists: %s\nUse Overwrite=true only when the ' ...
         'generated model should be replaced.'],modelFile);
end
if isfile(modelFile) && options.Overwrite
    delete(modelFile);
end
if bdIsLoaded(modelName)
    close_system(modelName,0);
end

new_system(modelName,'Model');
cleanup = onCleanup(@() close_if_loaded(modelName)); %#ok<NASGU>
load_system(modelName);

set_param(modelName, ...
    'SolverType','Fixed-step', ...
    'Solver','FixedStepDiscrete', ...
    'FixedStep','1', ...
    'StopTime','1');

p = cfg.batteryCooling;

add_block('simulink/Ports & Subsystems/In1', ...
    modelName+'/Sustained C-rate','Position',[30 168 60 182]);
add_block('simulink/Math Operations/Gain', ...
    modelName+'/Rated current at 1C', ...
    'Gain',number(p.capacity_Ah),'Position',[100 150 210 200]);
add_block('simulink/Math Operations/Product', ...
    modelName+'/Current squared','Inputs','**', ...
    'Position',[255 155 300 195]);
add_block('simulink/Math Operations/Gain', ...
    modelName+'/ACR heat floor per cell', ...
    'Gain',number(p.resistanceProxy_Ohm), ...
    'Position',[345 145 475 205]);
add_block('simulink/Math Operations/Gain', ...
    modelName+'/Pack heat floor', ...
    'Gain',number(p.seriesCells/1000), ...
    'Position',[530 65 650 115]);
add_block('simulink/Math Operations/Gain', ...
    modelName+'/Cell-to-coolant rise requirement', ...
    'Gain',number(p.baseResistance_KW), ...
    'Position',[530 225 680 275]);

add_block('simulink/Sources/Constant', ...
    modelName+'/Regen temperature limit', ...
    'Value',number(p.regenChargeCutoff_C), ...
    'Position',[735 175 785 205]);
add_block('simulink/Sources/Constant', ...
    modelName+'/Discharge temperature limit', ...
    'Value',number(p.absoluteOperatingLimit_C), ...
    'Position',[735 325 785 355]);
add_block('simulink/Math Operations/Sum', ...
    modelName+'/Maximum coolant for regen', ...
    'Inputs','+-','Position',[840 185 875 225]);
add_block('simulink/Math Operations/Sum', ...
    modelName+'/Maximum coolant for discharge', ...
    'Inputs','+-','Position',[840 305 875 345]);

add_outport(modelName,'Current A',[255 25 285 39],1);
add_outport(modelName,'Cell heat floor W',[530 145 560 159],2);
add_outport(modelName,'Pack heat floor kW',[710 83 740 97],3);
add_outport(modelName,'Required cell-to-coolant rise C',[735 245 765 259],4);
add_outport(modelName,'Maximum coolant for regen C',[940 193 970 207],5);
add_outport(modelName,'Maximum coolant for discharge C',[940 313 970 327],6);

add_line(modelName,'Sustained C-rate/1','Rated current at 1C/1');
add_line(modelName,'Rated current at 1C/1','Current squared/1');
add_line(modelName,'Rated current at 1C/1','Current squared/2');
add_line(modelName,'Rated current at 1C/1','Current A/1');
add_line(modelName,'Current squared/1','ACR heat floor per cell/1');
add_line(modelName,'ACR heat floor per cell/1','Cell heat floor W/1');
add_line(modelName,'ACR heat floor per cell/1','Pack heat floor/1');
add_line(modelName,'ACR heat floor per cell/1', ...
    'Cell-to-coolant rise requirement/1');
add_line(modelName,'Pack heat floor/1','Pack heat floor kW/1');
add_line(modelName,'Cell-to-coolant rise requirement/1', ...
    'Required cell-to-coolant rise C/1');
add_line(modelName,'Regen temperature limit/1', ...
    'Maximum coolant for regen/1');
add_line(modelName,'Cell-to-coolant rise requirement/1', ...
    'Maximum coolant for regen/2');
add_line(modelName,'Discharge temperature limit/1', ...
    'Maximum coolant for discharge/1');
add_line(modelName,'Cell-to-coolant rise requirement/1', ...
    'Maximum coolant for discharge/2');
add_line(modelName,'Maximum coolant for regen/1', ...
    'Maximum coolant for regen C/1');
add_line(modelName,'Maximum coolant for discharge/1', ...
    'Maximum coolant for discharge C/1');

annotation = sprintf([ ...
    'SUSTAINED REQUIREMENTS SCREEN ONLY\n' ...
    '0.40 mOhm is a 1 kHz ACR limit, so I^2R is a heat floor.\n' ...
    '3.10 K/W is reconstructed and requires validation.\n' ...
    'No coolant temperature, transient cell state or cooling capacity is predicted.']);
note = Simulink.Annotation(modelName,annotation);
note.Position = [30 390 650 475];

Simulink.BlockDiagram.arrangeSystem(modelName);
save_system(modelName,modelFile);
close_system(modelName,0);
end

function add_outport(modelName,name,position,portNumber)
add_block('simulink/Ports & Subsystems/Out1',modelName+"/"+string(name), ...
    'Port',num2str(portNumber),'Position',position);
end

function value = number(value)
value = sprintf('%.15g',value);
end

function close_if_loaded(modelName)
if bdIsLoaded(modelName)
    close_system(modelName,0);
end
end
