function geometry = read_radiator_geometry(filePath)
%READ_RADIATOR_GEOMETRY Import the candidate radiator geometry with its schema.

geometry = read_project_csv(filePath, ...
    {'Radiator','Application','CoreHeight_mm','CoreWidth_mm','CoreDepth_mm', ...
    'FrontalArea_m2','FlatTubeExternalWidth_mm', ...
    'FlatTubeExternalDepth_mm','AssumedTubeWallThickness_mm', ...
    'TubeQuantity','TubeLength_mm','FinWidth_mm','FinHeight_mm', ...
    'FinPitch_mm','AssumedFinThickness_mm','FinQuantity','FinLength_mm', ...
    'GeometryUse'}, ...
    {'CoreHeight_mm','CoreWidth_mm','CoreDepth_mm','FrontalArea_m2', ...
    'FlatTubeExternalWidth_mm','FlatTubeExternalDepth_mm', ...
    'AssumedTubeWallThickness_mm','TubeQuantity','TubeLength_mm', ...
    'FinWidth_mm','FinHeight_mm','FinPitch_mm','AssumedFinThickness_mm', ...
    'FinQuantity','FinLength_mm'});
end
