function modelFile = build_propulsion_thermal_sensitivity_simulink(cfg,options)
%BUILD_PROPULSION_THERMAL_SENSITIVITY_SIMULINK Build two-node model.
% Drive-unit heat, ambient temperature and radiator UA are model inputs.
% Thermal capacitances and motor-to-coolant resistance are exposed
% calibration assumptions. The model is not a validated temperature plant.

arguments
    cfg (1,1) struct = setup_project()
    options.Overwrite (1,1) logical = false
end

if isempty(ver('simulink'))
    error('EVThermal:SimulinkRequired', ...
        'Simulink is required to generate the propulsion thermal model.');
end

rootDir = cfg.project.rootDir;
modelDir = fullfile(rootDir,'models','propulsion_thermal_sensitivity');
modelName = "propulsion_thermal_sensitivity";
modelFile = fullfile(modelDir,modelName+".slx");

if isfile(modelFile) && ~options.Overwrite
    error('EVThermal:ModelExists', ...
        ['Model already exists: %s\nUse Overwrite=true only when the ' ...
         'generated model should be replaced.'],modelFile);
end
if isfile(modelFile) && options.Overwrite
    delete(modelFile);
end
if bdIsLoaded(modelName)
    close_system(modelName,0);
end

new_system(modelName,'Model');
cleanup = onCleanup(@() close_if_loaded(modelName)); %#ok<NASGU>
load_system(modelName);

set_param(modelName, ...
    'SolverType','Variable-step', ...
    'Solver','ode45', ...
    'StartTime','0', ...
    'StopTime','600', ...
    'SaveOutput','on', ...
    'OutputSaveName','yout', ...
    'SaveFormat','Dataset');

p = cfg.motorCooling.transient;

add_inport(modelName,'Drive-unit heat input kW',[30 65 60 79],1);
add_inport(modelName,'Ambient temperature input C',[30 305 60 319],2);
add_inport(modelName,'Radiator UA input W per K',[30 405 60 419],3);

add_block('simulink/Math Operations/Gain', ...
    modelName+"/Convert drive-unit heat to W", ...
    'Gain','1000','Position',[100 50 190 95]);
add_block('simulink/Math Operations/Sum',modelName+"/Motor heat balance", ...
    'Inputs','+-','Position',[315 60 350 100]);
add_block('simulink/Math Operations/Gain', ...
    modelName+"/Divide by motor thermal capacity", ...
    'Gain',number(1/p.motorThermalCapacity_JK), ...
    'Position',[395 55 515 105]);
add_block('simulink/Continuous/Integrator', ...
    modelName+"/Integrate motor temperature", ...
    'InitialCondition',number(p.initialMotorTemperature_C), ...
    'Position',[565 55 595 105]);

add_block('simulink/Math Operations/Sum', ...
    modelName+"/Motor coolant temperature difference",'Inputs','+-', ...
    'Position',[650 145 685 185]);
add_block('simulink/Math Operations/Gain', ...
    modelName+"/Calculate motor-to-coolant heat", ...
    'Gain',number(1/p.motorToCoolantResistance_KW), ...
    'Position',[730 140 880 190]);

add_block('simulink/Math Operations/Sum',modelName+"/Coolant heat balance", ...
    'Inputs','+-','Position',[315 225 350 265]);
add_block('simulink/Math Operations/Gain', ...
    modelName+"/Divide by coolant thermal capacity", ...
    'Gain',number(1/p.coolantThermalCapacity_JK), ...
    'Position',[395 220 515 270]);
add_block('simulink/Continuous/Integrator', ...
    modelName+"/Integrate coolant temperature", ...
    'InitialCondition',number(p.initialCoolantTemperature_C), ...
    'Position',[565 220 595 270]);

add_block('simulink/Math Operations/Sum', ...
    modelName+"/Coolant ambient temperature difference",'Inputs','+-', ...
    'Position',[140 300 175 340]);
add_block('simulink/Math Operations/Product', ...
    modelName+"/Calculate ideal radiator heat rejection", ...
    'Position',[220 325 265 365]);
add_block('simulink/Discontinuities/Saturation', ...
    modelName+"/Clamp radiator rejection nonnegative", ...
    'LowerLimit','0','UpperLimit','inf', ...
    'Position',[315 320 440 370]);

add_block('simulink/Math Operations/Gain', ...
    modelName+"/Convert motor heat transfer to kW", ...
    'Gain','0.001','Position',[920 140 1020 190]);
add_block('simulink/Math Operations/Gain', ...
    modelName+"/Convert radiator heat rejection to kW", ...
    'Gain','0.001','Position',[485 320 585 370]);

add_outport(modelName,'Motor temperature output C',[700 45 730 59],1);
add_outport(modelName,'Coolant temperature output C',[700 235 730 249],2);
add_outport(modelName,'Motor-to-coolant heat output kW',[1070 158 1100 172],3);
add_outport(modelName,'Radiator rejection output kW',[635 338 665 352],4);

add_line(modelName,'Drive-unit heat input kW/1', ...
    'Convert drive-unit heat to W/1');
add_line(modelName,'Convert drive-unit heat to W/1','Motor heat balance/1');
add_line(modelName,'Motor heat balance/1', ...
    'Divide by motor thermal capacity/1');
add_line(modelName,'Divide by motor thermal capacity/1', ...
    'Integrate motor temperature/1');
add_line(modelName,'Integrate motor temperature/1', ...
    'Motor temperature output C/1');
add_line(modelName,'Integrate motor temperature/1', ...
    'Motor coolant temperature difference/1');
add_line(modelName,'Integrate coolant temperature/1', ...
    'Motor coolant temperature difference/2');
add_line(modelName,'Motor coolant temperature difference/1', ...
    'Calculate motor-to-coolant heat/1');
add_line(modelName,'Calculate motor-to-coolant heat/1', ...
    'Motor heat balance/2');
add_line(modelName,'Calculate motor-to-coolant heat/1', ...
    'Coolant heat balance/1');
add_line(modelName,'Calculate motor-to-coolant heat/1', ...
    'Convert motor heat transfer to kW/1');
add_line(modelName,'Convert motor heat transfer to kW/1', ...
    'Motor-to-coolant heat output kW/1');
add_line(modelName,'Coolant heat balance/1', ...
    'Divide by coolant thermal capacity/1');
add_line(modelName,'Divide by coolant thermal capacity/1', ...
    'Integrate coolant temperature/1');
add_line(modelName,'Integrate coolant temperature/1', ...
    'Coolant temperature output C/1');
add_line(modelName,'Integrate coolant temperature/1', ...
    'Coolant ambient temperature difference/1');
add_line(modelName,'Ambient temperature input C/1', ...
    'Coolant ambient temperature difference/2');
add_line(modelName,'Coolant ambient temperature difference/1', ...
    'Calculate ideal radiator heat rejection/1');
add_line(modelName,'Radiator UA input W per K/1', ...
    'Calculate ideal radiator heat rejection/2');
add_line(modelName,'Calculate ideal radiator heat rejection/1', ...
    'Clamp radiator rejection nonnegative/1');
add_line(modelName,'Clamp radiator rejection nonnegative/1', ...
    'Coolant heat balance/2');
add_line(modelName,'Clamp radiator rejection nonnegative/1', ...
    'Convert radiator heat rejection to kW/1');
add_line(modelName,'Convert radiator heat rejection to kW/1', ...
    'Radiator rejection output kW/1');

annotation = sprintf([ ...
    'UNCALIBRATED SENSITIVITY MODEL\n' ...
    'Motor capacity: %.0f J/K (assumed)\n' ...
    'Coolant capacity: %.0f J/K (assumed)\n' ...
    'Motor-to-coolant resistance: %.4f K/W (assumed)\n' ...
    'Radiator UA is an external scenario input, not a verified map.'], ...
    p.motorThermalCapacity_JK,p.coolantThermalCapacity_JK, ...
    p.motorToCoolantResistance_KW);
note = Simulink.Annotation(modelName,annotation);
note.Position = [30 500 630 600];

Simulink.BlockDiagram.arrangeSystem(modelName);
save_system(modelName,modelFile);
close_system(modelName,0);
end

function add_inport(modelName,name,position,portNumber)
add_block('simulink/Ports & Subsystems/In1',modelName+"/"+string(name), ...
    'Port',num2str(portNumber),'Position',position);
end

function add_outport(modelName,name,position,portNumber)
add_block('simulink/Ports & Subsystems/Out1',modelName+"/"+string(name), ...
    'Port',num2str(portNumber),'Position',position);
end

function value = number(value)
value = sprintf('%.15g',value);
end

function close_if_loaded(modelName)
if bdIsLoaded(modelName)
    close_system(modelName,0);
end
end
