function out = run_shared_compressor(cfg,batteryCooling,cabinCooling)
%RUN_SHARED_COMPRESSOR Merge battery and cabin demand at one compressor.
% The upstream battery and cabin result files remain independent. This
% module is the only location where their demands are combined.

p = cfg.sharedCompressor;
outputDir = fullfile(cfg.project.outputDir,"shared_compressor");
ensure_output_folder(outputDir);

out.map = read_project_csv(p.files.performanceMap, ...
    {'RPM','EvaporatorTemperature_C','CoolingCapacity_kW', ...
     'InputPower_kW','Current_A','COP_WW','EvidenceStatus'}, ...
    {'RPM','EvaporatorTemperature_C','CoolingCapacity_kW', ...
     'InputPower_kW','Current_A','COP_WW'});
out.mapOperatingPoint = evaluate_compressor_map( ...
    out.map,p.mapSpeed_rpm,p.mapEvaporator_C);
out.candidates = read_project_csv(p.files.candidates, ...
    {'Model','Displacement_cc','CoolingCapacity_kW','InputPower_kW', ...
     'Speed_rpm','Voltage_V','EvidenceCondition'}, ...
    {'Displacement_cc','CoolingCapacity_kW','InputPower_kW', ...
     'Speed_rpm','Voltage_V'});

nCycles = numel(batteryCooling.details);
comparisonRows = cell(nCycles,1);
for i = 1:nCycles
    comparisonRows{i} = calculate_cycle_compressor_check( ...
        batteryCooling.details{i},out.candidates, ...
        cabinCooling.summary.RecoveredPartialSensibleLoad_kW, ...
        p.allocationPriority);
end
out.comparison = vertcat(comparisonRows{:});
out.currentResult = build_current_result( ...
    out.comparison,batteryCooling.summary,cabinCooling.summary, ...
    cfg.batteryCooling,p);

writetable(out.mapOperatingPoint,fullfile(outputDir, ...
    "compressor_map_operating_point.csv"));
writetable(out.candidates,fullfile(outputDir, ...
    "compressor_candidates.csv"));
writetable(out.comparison,fullfile(outputDir, ...
    "shared_compressor_comparison.csv"));
writetable(out.currentResult,fullfile(outputDir, ...
    "shared_cooling_current_result.csv"));
plot_shared_compressor_capacity( ...
    batteryCooling.details,cabinCooling.summary,out.candidates,outputDir);
end

function plot_shared_compressor_capacity( ...
        batteryDetails,cabinSummary,candidates,outputDir)
fig = figure('Visible','off','Color','w','Position',[100 100 1250 780]);
layout = tiledlayout(numel(batteryDetails),1,'TileSpacing','compact');
cabinDuty_kW = cabinSummary.RecoveredPartialSensibleLoad_kW;
colors = lines(height(candidates));
for i = 1:numel(batteryDetails)
    nexttile;
    combinedDemand_kW = ...
        batteryDetails{i}.BatteryCoolingRequest_kW+cabinDuty_kW;
    plot(batteryDetails{i}.Time_s,combinedDemand_kW,'k','LineWidth',1.4, ...
        'DisplayName','Combined demand');
    hold on;
    for j = 1:height(candidates)
        yline(candidates.CoolingCapacity_kW(j),'--', ...
            candidates.Model(j),'Color',colors(j,:), ...
            'LineWidth',1.2,'LabelHorizontalAlignment','left');
    end
    grid on;
    ylabel('Cooling duty (kW)');
    title(batteryDetails{i}.Cycle(1));
end
xlabel(layout,'Time (s)');
title(layout,'Shared compressor capacity against cabin and battery demand');
exportgraphics(fig,fullfile(outputDir,"shared_compressor_capacity.png"), ...
    'Resolution',180);
close(fig);
end

function current = build_current_result( ...
        comparison,batterySummary,cabinSummary,batteryConfig,p)
current = comparison;
[found,index] = ismember(current.Cycle,batterySummary.Cycle);
if ~all(found)
    error('EVThermal:MissingBatterySummary', ...
        'Every compressor result requires a matching battery-cycle summary.');
end
current.PeakBatteryHeat_kW = batterySummary.PeakBatteryHeat_kW(index);
current.PeakEstimatedCellTemperature_C = ...
    batterySummary.PeakEstimatedCellTemperature_C(index);
current.BatteryTemperatureWithinLimit = ...
    batterySummary.CellTemperatureWithinLimit(index);
current.KarachiDesignAmbient_C = repmat( ...
    cabinSummary.DesignAmbient_C,height(current),1);
current.CabinModelBoundary = repmat( ...
    cabinSummary.ModelBoundary,height(current),1);
current.BatteryModelBoundary = repmat( ...
    batteryConfig.modelBoundary,height(current),1);
current.CompressorEvidenceBoundary = repmat(p.modelBoundary,height(current),1);
current.GrossCapacityPass = current.GrossPeakCapacityMargin_kW>=0;
current.OverallScreeningPass = current.GrossCapacityPass & ...
    current.BatteryTemperatureWithinLimit;
end

function ensure_output_folder(folder)
if ~isfolder(folder)
    mkdir(folder);
end
end
